export const exercisesTroisieme = [
  {
    chapterName: "calcul-litteral",
    id: "troisieme-calcul-litteral-1",
    isCompleted: false,
    scoreAverage: 0,
    level: "Troisième",
    lesson: "Calcul Littéral",
    number: 1,
    limitDate: "",
    validationDate: "",
    statements: "Développer, réduire et ordonner les expressions suivantes :",
    questionsSolutions: [
      {
        time: 3,
        question: ["", "$\\mathrm{A}=3(4x+7)+4(2x-9)$"],
        imgName: "",
        solution: [
          "$\\mathrm{A}= 3 × 4x + 3 × 7 + 4 × 2x + 4 × (-9)$",
          "$\\mathrm{A}= 12x + 21 + 8x - 36$",
          "$\\mathrm{A}= 20x - 15$",
        ],
      },
      {
        time: 3,
        question: ["", "$\\mathrm{B}=7x(2x-5)-x(2x-5)$"],
        imgName: "",
        solution: [
          "$\\mathrm{B}=7x × 2x + 7x × (-5) -x × 2x -x × (-5)$",
          "$\\mathrm{B}= 14x^2 - 35x -2x^2 + 5x$",
          "$\\mathrm{B}= 12x^2 - 30x$",
        ],
      },
      {
        time: 300,
        question: ["", "$\\mathrm{C}=(2x+5)(3x+7)$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$\\mathrm{D}=(2x-5)(3x-2)$"],
        imgName: "",
        solution: [],
      },
    ],
  },

  {
    chapterName: "calcul-litteral",
    id: "troisieme-calcul-litteral-2",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Calcul Littéral",
    level: "Troisième",
    number: 2,
    limitDate: "",
    validationDate: "",
    statements: "Développer, réduire et ordonner les expressions suivantes :",
    questionsSolutions: [
      {
        time: 300,
        question: ["", "$\\mathrm{E}=(2 x+3)(5 x-8)-(2 x-4)(5 x-1)$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$\\mathrm{F}=(5 x-2)(5 x-8)-(3 x-5)(x+7)$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$\\mathrm{G}=2(x+7)(3-2 x)+(5 x-2)(4 x+1)$"],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "calcul-litteral",
    id: "troisieme-calcul-litteral-3",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Calcul Littéral",
    level: "Troisième",
    number: 3,
    limitDate: "",
    validationDate: "",
    statements:
      "Développer, réduire et ordonner les expressions suivantes sans étape de calcul :",
    questionsSolutions: [
      {
        time: 300,
        question: ["", "$\\mathrm{H}=(x+5)^{2}$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$\\mathrm{I}=(4 x+6)^{2}$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$\\mathrm{J}=(x-5)^{2}$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$\\mathrm{K}=(3 x-7)^{2}$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$\\mathrm{L}=(y+3)(y-3)$"],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "calcul-litteral",
    id: "troisieme-calcul-litteral-4",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Calcul Littéral",
    level: "Troisième",
    number: 4,
    limitDate: "",
    validationDate: "",
    statements: "Développer, réduire et ordonner les expressions suivantes :",
    questionsSolutions: [
      {
        time: 300,
        question: ["", "$\\mathrm{N}=\\left(3 x-\\frac{2}{3}\\right)^{2}$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "",
          "$\\mathrm{P}=\\left(\\frac{5}{2}+\\frac{1}{3} x\\right)\\left(\\frac{1}{3} x-\\frac{5}{2}\\right)$",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$\\mathrm{Q}=(x+2)^{2}-6(3 x-5)^{2}$"],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "calcul-litteral",
    id: "troisieme-calcul-litteral-5",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Calcul Littéral",
    level: "Troisième",
    number: 5,
    limitDate: "",
    validationDate: "",
    statements: "Compléter les expressions suivantes :",
    questionsSolutions: [
      {
        time: 300,
        question: ["", "$\\quad( \\ldots-\\ldots)^{2}=16 x^{2}-72 x+\\ldots$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$(5 x- \\ldots)^{2}=\\ldots-\\ldots+36$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$(\\ldots+\\ldots)^{2}=\\ldots+70 x+25$"],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "calcul-litteral",
    id: "troisieme-calcul-litteral-6",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Calcul Littéral",
    level: "Troisième",
    number: 6,
    limitDate: "",
    validationDate: "",
    statements: "Factoriser les expressions suivantes :",
    questionsSolutions: [
      {
        time: 300,
        question: ["", "$\\mathrm{A}=(x+2)(2 x-1)+(x+2)(3 x+2)$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$\\mathrm{B}=(3 x+7)(2 x-9)-(3 x+7)(5 x-7)$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$\\mathrm{C}=(8 y+3)(5 y+7)-3(8 y+3)(2 y-1)$"],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "calcul-litteral",
    id: "troisieme-calcul-litteral-7",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Calcul Littéral",
    level: "Troisième",
    number: 7,
    limitDate: "",
    validationDate: "",
    statements: "Factoriser les expressions suivantes :",
    questionsSolutions: [
      {
        time: 300,
        question: ["", "$\\mathrm{D}=(2 x+3)^{2}+(x-2)(2 x+3)$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$\\mathrm{E}=(2 t-7)-(5 t+1)(2 t-7)$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$\\mathrm{G}=(2 t-5)^{2}+(2 t-5)(x-1)+2 t-5$"],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "calcul-litteral",
    id: "troisieme-calcul-litteral-8",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Calcul Littéral",
    level: "Troisième",
    number: 8,
    limitDate: "",
    validationDate: "",
    statements: "Résoudre les équations suivantes :",
    questionsSolutions: [
      {
        time: 300,
        question: ["", "$\\quad-2(2 x-4)=6 x-(-3+x)$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$4 x-2+(5 x-1)=-3(7-x)$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$\\frac{x+5}{2}-\\frac{2 x-7}{5}=2+\\frac{3 x}{10}$"],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "calcul-litteral",
    id: "troisieme-calcul-litteral-9",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Calcul Littéral",
    level: "Troisième",
    number: 9,
    limitDate: "",
    validationDate: "",
    statements: "Résoudre les équations suivantes :",
    questionsSolutions: [
      {
        time: 300,
        question: ["", "$4(2+3 x)-(x-5)=0$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$50 x^{2}=8$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$4 x^{2}+4 x=-1$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$\\quad(9 x-4)(-2+5 x)-(9 x-4)(3 x-5)=0$"],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "calcul-litteral",
    id: "troisieme-calcul-litteral-10",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Calcul Littéral",
    level: "Troisième",
    number: 10,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "",
          "Factoriser $\\ 4 x^{2}-12x+9.$",
          "Factoriser $\\ (2 x-3)^{2}-4.$",
          "En déduire une factorisation de $\\ 4 x^{2}-12 x+5.$",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "arithmetique",
    id: "troisieme-arithmetique-1",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Arithmétique",
    level: "Troisième",
    number: 1,
    limitDate: "",
    validationDate: "",
    statements: "Diviseurs, multiples, critères de divisibilité.",
    questionsSolutions: [
      {
        time: 300,
        question: ["", "Effectuer la division euclidienne de : 31 par 4"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "Effectuer la division euclidienne de : 79 par 9"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "Effectuer la division euclidienne de : 84 par 7"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "Effectuer la division euclidienne de : 3 par 5"],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "arithmetique",
    id: "troisieme-arithmetique-2",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Arithmétique",
    level: "Troisième",
    number: 2,
    limitDate: "",
    validationDate: "",
    statements: "Diviseurs, multiples, critères de divisibilité.",
    questionsSolutions: [
      {
        time: 300,
        question: ["", "Donner cinq multiples du nombre : 8"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "Donner cinq multiples du nombre : 11"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "Donner cinq multiples du nombre : 12"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "Donner cinq multiples du nombre : 15"],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "arithmetique",
    id: "troisieme-arithmetique-3",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Arithmétique",
    level: "Troisième",
    number: 3,
    limitDate: "",
    validationDate: "",
    statements: "Diviseurs, multiples, critères de divisibilité.",
    questionsSolutions: [
      {
        time: 300,
        question: ["", "Citer tous les diviseurs du nombre : 6"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "Citer tous les diviseurs du nombre : 17"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "Citer tous les diviseurs du nombre : 25"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "Citer tous les diviseurs du nombre : 35"],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "arithmetique",
    id: "troisieme-arithmetique-4",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Arithmétique",
    level: "Troisième",
    number: 4,
    limitDate: "",
    validationDate: "",
    statements: "Diviseurs, multiples, critères de divisibilité.",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Je suis un nombre entier compris entre 100 et 400. Je suis pair. Je suis divisible par 11. J’ai aussi 3 et 5 comme diviseurs.",
          "Qui suis-je ?",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Un livreur range 752 DVD dans des caisses qui peuvent en contenir 40.",
          "Combien faut-il de caisses pour ranger tous les DVD ? ",
          "Combien de DVD contiendra la caisse non pleine ?",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "6 798 supporters d’un club de rugby doivent faire un déplacement en car pour soutenir leur équipe. Chaque car dispose de 55 places.",
          "Combien de cars faut-il réserver ?",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "arithmetique",
    id: "troisieme-arithmetique-5",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Arithmétique",
    level: "Troisième",
    number: 5,
    limitDate: "",
    validationDate: "",
    statements: "Nombres premiers et fractions irréductibles.",
    questionsSolutions: [
      {
        time: 300,
        question: ["", "Rendre irréductible : $\\frac{55}{15}$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "Rendre irréductible : $\\frac{14}{16}$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "Rendre irréductible : $\\frac{270}{120}$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "Rendre irréductible : $\\frac{14}{49}$"],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "arithmetique",
    id: "troisieme-arithmetique-6",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Arithmétique",
    level: "Troisième",
    number: 6,
    limitDate: "",
    validationDate: "",
    statements: "Nombres premiers et fractions irréductibles.",
    questionsSolutions: [
      {
        time: 300,
        question: ["", "Écrire trois diviseurs de 12."],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "Écrire quatre diviseurs de 18."],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "Écrire quatre diviseurs de 75."],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "Écrire trois diviseurs de 64."],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "arithmetique",
    id: "troisieme-arithmetique-7",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Arithmétique",
    level: "Troisième",
    number: 7,
    limitDate: "",
    validationDate: "",
    statements: "Nombres premiers et fractions irréductibles.",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "",
          "Décomposer 25 en produits de facteurs premiers.",
          "Décomposer 125 en produits de facteurs premiers.",
          "Décomposer 456 en produits de facteurs premiers.",
          "Décomposer 2018 en produits de facteurs premiers.",
          "Rendre irréductible la fraction : $\\frac{25}{125}$ ",
          "Rendre irréductible la fraction : $\\frac{2018}{456}$",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "arithmetique",
    id: "troisieme-arithmetique-8",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Arithmétique",
    level: "Troisième",
    number: 8,
    limitDate: "",
    validationDate: "",
    statements:
      "Rendre irréductible les fractions suivantes en décomposant leur numérateur et dénominateur en produit de facteurs premiers :",
    questionsSolutions: [
      {
        time: 300,
        question: ["", "A = $\\frac{128}{244}$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "B = $\\frac{1404}{3 465}$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "C = $\\frac{408}{578}$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "D = $\\frac{845}{1 235}$"],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "arithmetique",
    id: "troisieme-arithmetique-9",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Arithmétique",
    level: "Troisième",
    number: 9,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "",
          " Rendre irréductible la fraction $\\frac{425}{100}$",
          "puis calculer A =$\\frac{425}{100} - \\frac{3}{2}$",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Flavien veut répartir 760 dragées au chocolat et 1 045 dragées aux amandes dans des sachets ayant la même répartition de dragées au chocolat et aux amandes.",
          "Peut-il faire 76 sachets ? Justifier.",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "arithmetique",
    id: "troisieme-arithmetique-10",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Arithmétique",
    level: "Troisième",
    number: 10,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Une ouvrière dispose de plaques de métal de 110 cm de longueur et de 88 cm de largeur. Elle a reçu la consigne suivante : « Découpez dans ces plaques des carrés tous identiques, dont les longueurs des côtés sont un nombre entier de cm, et de façon à ne pas avoir de perte. »",
          "Peut-elle choisir de découper des plaques de 10 cm de côté ?",
          "Peut-elle choisir de découper des plaques de 11 cm de côté ?",
          "On lui impose désormais de découper des carrés les plus grands possibles. Quelle sera la longueur du côté d’un carré ? ",
          "Combien y aura-t-il de carrés par plaques ?",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "theoreme-de-pythagore",
    id: "troisieme-theoreme-de-pythagore-1",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Théorème de Pythagore",
    level: "Troisième",
    number: 1,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Soit le triangle TGV rectangle en G où GT = 54 mm et GV = 72 mm.",
          "Calculer la valeur exacte de TV",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Soit le triangle YUV tel que YU = 65 mm, YV = 72 mm et UV = 97 mm.",
          "Ce triangle est-il rectangle ?",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "theoreme-de-pythagore",
    id: "troisieme-theoreme-de-pythagore-2",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Théorème de Pythagore",
    level: "Troisième",
    number: 2,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "",
          "1. Calculer AC.",
          "2. Le triangle ACD est-il rectangle ? ",
        ],
        imgName: "theoreme-de-pythagore-img1",
        solution: [],
      },
      {
        time: 300,
        question: [
          "ABCDEFGH est un parallélépipède rectangle.",
          "1. Calculer AC.",
          "2. Calculer AG.",
        ],
        imgName: "theoreme-de-pythagore-img3",
        solution: [],
      },
    ],
  },
  {
    chapterName: "theoreme-de-pythagore",
    id: "troisieme-theoreme-de-pythagore-3",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Théorème de Pythagore",
    level: "Troisième",
    number: 3,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "ABCD est un carré de côté 10 cm.",
          "Calculer EF",
          "Calculer EC",
          " Calculer FC",
          "Le triangle FEC est-il rectangle ?",
        ],
        imgName: "theoreme-de-pythagore-img2",
        solution: [],
      },
      {
        time: 300,
        question: [
          "ABCD est un rectangle de côtés AB cm 12 et AD cm 9. Sur le côté [BC] on place le point E tel que AE 13 cm. Sur le côté [DC] on place le point F tel que DF 5 cm.",
          " Calculer la longueur AF.",
          "Calculer la longueur BE.",
          "Calculer les longueurs CE",
          "Calculer les longueurs CF",
          "puis la longueur EF",
          "Le triangle AFE est-il rectangle ?",
        ],
        imgName: "theoreme-de-pythagore-img4",
        solution: [],
      },
    ],
  },
  {
    chapterName: "theoreme-de-pythagore",
    id: "troisieme-theoreme-de-pythagore-4",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Théorème de Pythagore",
    level: "Troisième",
    number: 4,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Jean-Michel est propriétaire d'un champ, représenté par le triangle ABC ci-dessous. Il achète à son voisin le champ adjacent, représenté par le triangle ADC. On obtient ainsi un nouveau champ formé par le quadrilatère ABCD. Jean Michel sait que le périmètre de son champ ABC est de 154 mètres et que BC = 56 m. Son voisin l'informe que le périmètre du champ ADC est de 144 mètres et que AC = 65 m. De plus, il sait que AD = 16 m.",
          "1. a. Justifier que les longueurs AB et DC sont respectivement égales à 33 m et 63 m.",
          "1. b. Calculer le périmètre du champ ABCD.",
          "2. Démontrer que le triangle ADC est rectangle en D. On admet que le triangle ABC est rectangle en B.",
          "3. Calculer l'aire du champ ABCD.",
          "4. Jean-Michel veut clôturer son champ avec du grillage. Il se rend chez son commerçant habituel et tombe sur l'annonce suivante : Combien va-t-il payer pour clôturer son champ? Sachant que 1mètre de grillage coûte 0,85€.",
        ],
        imgName: "theoreme-de-pythagore-img5",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Le but de l’exercice est de déterminer l’aire du triangle BCD. (OC) est la hauteur du triangle BCD issue de C. On rappelle la formule : Aire = (bxh)/2",
          "1. a. Calculer la longueur OB.",
          "1. b. Calculer la longueur OC.",
          "1. c. Calculer la longueur OD.",
          "2. En utilisant les résultats du 1, calculer l’aire du triangle BCD.",
        ],
        imgName: "theoreme-de-pythagore-img7",
        solution: [],
      },
    ],
  },
  {
    chapterName: "theoreme-de-pythagore",
    id: "troisieme-theoreme-de-pythagore-5",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Théorème de Pythagore",
    level: "Troisième",
    number: 5,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Sur le dessin ci-dessus, les points A,B et E sont alignés, et C le milieu de [BD]",
          "1. Quelle est la nature du triangle ABC ?",
          "2. En déduire la nature du triangle BDE",
          "3. Calculer ED. Arrondir le résultat au dixième.",
        ],
        imgName: "theoreme-de-pythagore-img6",
        solution: [],
      },
      {
        time: 300,
        question: [
          "ABCDEFGH est un pavé droit de longueur 4 cm, de largeur 3 cm et de hauteur 12 cm.",
          "Calculer la longueur EG",
          "Puis calculer la diagonale AG.",
        ],
        imgName: "theoreme-de-pythagore-img8",
        solution: [],
      },
    ],
  },
  {
    chapterName: "fonctions",
    id: "fonctions-1",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Fonctions",
    level: "Troisième",
    number: 1,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Soit la fonction f définie par f(x) = 8x",
          "Détermine f(2)",
          "Détermine f(-3)",
          "Détermine f(0)",
          "Quelle est l'image de -5 par la fonction f ?",
          "Quelle est l'image de $\\frac{1}{8}$ $par la fonction f ?$",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Voici un tableau de valeurs correspondant à une fonction f.",
          "Quelle est l'image de 3 par la fonction f ?",
          "Quel nombre a pour image -3 par la fonction f ?",
          "Quel nombre a pour antécédent -4 par la fonction f ?",
          "Quels sont les nombres qui ont la même image ?",
        ],
        imgName: "fonctions-img1",
        solution: [],
      },
    ],
  },
  {
    chapterName: "fonctions",
    id: "fonctions-2",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Fonctions",
    level: "Troisième",
    number: 2,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Ce graphique représente une fonction h",
          "Quelle est l'image de 0 par la fonction h ?",
          "Quels nombres ont pour image 0 par la fonction h ?",
          "Donne une valeur de : l'image de 4 par la fonction h ",
          "Donne une valeur de : l'image de -3 par la fonction h ",
        ],
        imgName: "fonctions-img2",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Sur le graphique ci-dessus, des fonctions f, g, h, k et u ont été représentées.",
          "Parmi ces fonctions, indique celles qui sont affines. (Tu préciseras celles qui sont linéaires.) (Séparer vos réponses avec des points-virgules)",
        ],
        imgName: "fonctions-img3",
        solution: [],
      },
    ],
  },
  {
    chapterName: "fonctions",
    id: "fonctions-3",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Fonctions",
    level: "Troisième",
    number: 3,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Le graphique ci-dessus représente des fonctions f et g. (Séparer vos réponses avec des points-virgules)",
          "Déterminer les images des nombres 0 ; 1 et -4.",
          "Déterminer les antécédents des nombres 3 ; -5 et 5.",
        ],
        imgName: "fonctions-img4",
        solution: [],
      },
      {
        time: 300,
        question: [
          "On considère la fonction g définie par g(x) = (x - 3)(x + 1).",
          "Quelle est l'image de 2 par g ?",
          "Quelle est l'image de -5 par g ?",
          "Quels sont les antécédents de 0 par g ?",
          "Donne un antécédent de -3 par g.",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "fonctions",
    id: "fonctions-4",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Fonctions",
    level: "Troisième",
    number: 4,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Sur le graphique ci-dessus, des fonctions f, g, h, k et u ont été représentées. Détermine chacune des cinq fonctions",
          "f(x) =",
          "g(x) =",
          "h(x) =",
          "k(x) =",
          "u(x) =",
        ],
        imgName: "fonctions-img5",
        solution: [],
      },
      {
        time: 300,
        question: [
          "La fonction k est définie par k(x) = 4x² - 3.",
          "Quelle est l'image de -0,5 par k ?",
          "Quel nombre a pour antécédent 1 par k ?",
          " Quel est l'antécédent de -3 par k ?",
          "Quels nombres ont pour image -2 par k ?",
          " Pour quelles valeurs de x a-t-on k(x) = 0 ?",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "theoreme-de-thales",
    id: "theoreme-de-thales-1",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Théorème de Thalès",
    level: "Troisième",
    number: 1,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "E est un point de [MP] et F un point de [MN]. (EF) et (PN) sont parallèles.",
          "Calculer MN.",
          "Quel est le coefficient qui permet de passer du triangle MEF au triangle MPN ?",
        ],
        imgName: "theoreme-de-thales-img1",
        solution: [],
      },
      {
        time: 300,
        question: [
          "E est un point de [AB] et F un point de [AC]. Les droites (EF) et (BC) sont parallèles.",
          " Calculer EF.",
          " Puis calculer AC.",
        ],
        imgName: "theoreme-de-thales-img2",
        solution: [],
      },
    ],
  },
  {
    chapterName: "theoreme-de-thales",
    id: "theoreme-de-thales-2",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Théorème de Thalès",
    level: "Troisième",
    number: 2,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Les droites (MN) et (BC) sont parallèles et AB= 10cm.",
          "Calculer AC.",
          "Calculer BC et AM.",
          "Le triangle ABC est-il rectangle ?",
        ],
        imgName: "theoreme-de-thales-img3",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Construis un triangle ABC rectangle en B tel que AB = 4 cm ; BC = 3 cm et AC = 5 cm. Sur la demi-droite [BA), place le point E tel que BE = 8,8 cm. Trace la droite parallèle à (AC) passant par E, elle recoupe la droite (BC) en F.",
          "Calcule EF.",
          "Calcule BF.",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "theoreme-de-thales",
    id: "theoreme-de-thales-3",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Théorème de Thalès",
    level: "Troisième",
    number: 3,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Pour gravir de très fortes pentes, un funiculaire utilise une traction par câble. Ci-dessus, un croquis d’une telle voie. La longueur DA de la voie est de 125 m.",
          "1) a) Que peux-tu dire des droites (PM) et (AH) ?",
          "1) b) Calculer MP",
          "2) a) Lorsque le funiculaire a parcouru 1 m, de quelle hauteur s’est-il élevé ?",
          "2) b) Quelle distance a parcouru le funiculaire lorsqu’il s’est élevé de 50 m ? Arrondir le résultat au dixième.",
        ],
        imgName: "theoreme-de-thales-img4",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Dans la figure ci-dessus, qui n’est pas à l’échelle, on sait que : (BC) // (DE). B, A et E sont alignés. C, A et D sont alignés.",
          "Calculer la longueur du segment [BC] ",
        ],
        imgName: "theoreme-de-thales-img5",
        solution: [],
      },
    ],
  },
  {
    chapterName: "theoreme-de-thales",
    id: "theoreme-de-thales-4",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Théorème de Thalès",
    level: "Troisième",
    number: 4,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Sur la figure ci-dessus E, G, I et F, G, H sont alignés, (EF) // (HI), EF = 25 cm , GF = 7 cm , EG = 24 cm et GH = 20 cm",
          "Quelle est la nature du triangle EFG ?",
          "Calculez KL et que K est le milieu de [HI].",
          "Calculez KI.",
        ],
        imgName: "theoreme-de-thales-img6",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Sur la figure ci-dessus, ABCD est un parallélogramme. Une droite coupe [BD] en E, [DC] en F et (BC) en G de telle sorte que AE = 5 cm et EF = 3 cm .",
          "Calculer FG",
        ],
        imgName: "theoreme-de-thales-img7",
        solution: [],
      },
    ],
  },
  {
    chapterName: "theoreme-de-thales",
    id: "theoreme-de-thales-5",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Théorème de Thalès",
    level: "Troisième",
    number: 5,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Sur la figure ci-dessus, on sait que OA = 2 ; AB = 1,6 ;  CD = 3,2 ; AC = 5,5 ; OE = 2,5 ; FD = 9 , (AC) // (BD) et (EC) // (FD).",
          "Calculez OC.",
          "Calculez BD.",
          "Calculez EF",
          "Calculez EC.",
          "Les droites (AE) et (BF) sont-elles parallèles?",
          "Sachant que le périmètre du triangle ACE vaut 14,62 ; Calculez le périmètre du triangle BDF .",
        ],
        imgName: "theoreme-de-thales-img8",
        solution: [],
      },
    ],
  },
  {
    chapterName: "proportionnalite",
    id: "proportionnalite-1",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Proportionnalité",
    level: "Troisième",
    number: 1,
    limitDate: "",
    validationDate: "",
    statements: "Proportionnalité:",
    questionsSolutions: [
      {
        time: 300,
        question: ["", "Compléter le tableau de proportionnalité ci-dessus : "],
        editTableData: [
          [
            { value: "1", locked: true },
            { value: "3", locked: true },
            { value: "6", locked: true },
            { value: "", locked: false },
            { value: "", locked: false },
            { value: "", locked: false },
            { value: "25", locked: true },
          ],
          [
            { value: "", locked: false },
            { value: "", locked: false },
            { value: "", locked: false },
            { value: "4", locked: true },
            { value: "8", locked: true },
            { value: "18", locked: true },
            { value: "", locked: false },
          ],
        ],
        imgName: "proportionnalite-img11",
        solution: [],
      },
      {
        time: 300,
        question: ["", "Compléter le tableau de proportionnalité ci-dessus : "],
        imgName: "proportionnalite-img12",
        editTableData: [
          [
            { value: "3", locked: true },
            { value: "12", locked: true },
            { value: "15", locked: true },
            { value: "18", locked: true },
            { value: "26", locked: true },
            { value: "32", locked: true },
            { value: "40", locked: true },
          ],
          [
            { value: "", locked: false },
            { value: "", locked: false },
            { value: "", locked: false },
            { value: "", locked: false },
            { value: "", locked: false },
            { value: "", locked: false },
            { value: "", locked: false },
          ],
        ],
        solution: [],
      },
      {
        time: 300,
        question: ["", "Compléter le tableau de proportionnalité ci-dessus : "],
        imgName: "proportionnalite-img13",
        editTableData: [
          [
            { value: "10", locked: true },
            { value: "", locked: false },
            { value: "5", locked: true },
            { value: "", locked: false },
            { value: "2", locked: true },
            { value: "", locked: false },
          ],
          [
            { value: "", locked: false },
            { value: "12", locked: true },
            { value: "", locked: false },
            { value: "48", locked: true },
            { value: "", locked: false },
            { value: "1,2", locked: true },
          ],
        ],
        solution: [],
      },
    ],
  },
  {
    chapterName: "proportionnalite",
    id: "proportionnalite-2",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Proportionnalité",
    level: "Troisième",
    number: 2,
    limitDate: "",
    validationDate: "",
    statements: "Proportionnalité:",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Une feuille de papier à dessin de longueur 65 cm pèse 240 g. En supposant que la largeur reste la même",
          "Calculer la longueur, en cm, d’une feuille de papier dont la masse est de 144 g.",
          "Calculer la masse, en grammes, d’une feuille de papier mesurant 1,30 m de long.",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Un pot de 0,75 litre de vitrificateur permet de couvrir 9 m2 de parquet.",
          "Quelle quantité de vitrificateur permet de couvrir une surface de 15 m2 ?",
          "Quelle surface peut-on recouvrir avec 3 litres de vitrificateur ?",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "proportionnalite",
    id: "proportionnalite-3",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Proportionnalité",
    level: "Troisième",
    number: 3,
    limitDate: "",
    validationDate: "",
    statements: "Proportionnalité:",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Une moto de grosse cylindrée (900 cm3) consomme en moyenne 6,5 litres de sans plomb 95 pour un trajet de 130 km.",
          "Déterminer la consommation de carburant pour un trajet de 600 km.",
          "Déterminer le nombre de kilomètres parcourus si la consommation est de 18 litres.",
          "Le motard paie à une station service 0,96 € le litre de carburant. Combien dépensera-t-il pour un trajet de 850 km ?",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Dans une recette de cuisine, la quantité de pommes de terre entrant dans la composition d’un plat est proportionnelle au nombre de personnes partageant le repas.",
          " Déterminer la masse de pommes de terre nécessaire pour un repas de 6 personnes.",
          "Déterminer le nombre de personnes partageant le repas si le plat est composé de 120 g de pommes de terre.",
        ],
        imgName: "proportionnalite-img3",
        solution: [],
      },
    ],
  },
  {
    chapterName: "proportionnalite",
    id: "proportionnalite-4",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Proportionnalité",
    level: "Troisième",
    number: 4,
    limitDate: "",
    validationDate: "",
    statements: "Pourcentages:",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Avant les soldes, Mélanie avait repéré un pantalon à 70 € et un pull à 60 €. Elle décide d’attendre les soldes. Le pantalon est soldé à – 40% et le pull à – 60% .",
          "Calculer le montant du pantalon pendant les soldes",
          "Calculer le montant du pull pendant les soldes",
          "Combien Mélanie va-t-elle dépenser ?",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Clara achète 3,5 kg de pommes. Elle paie 9,10 € . ",
          "Combien coûte 8 kg de pomme ?",
          "Amélie a aussi acheté des pommes, elle en a pris 4,2 kg et elle a payé 10,5 €. Est-ce normal ?",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "proportionnalite",
    id: "proportionnalite-5",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Proportionnalité",
    level: "Troisième",
    number: 5,
    limitDate: "",
    validationDate: "",
    statements: "Pourcentages:",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Dans une entreprise, les salaires ont augmenté de 1,5% en juillet.",
          "M Dupont avait un salaire de 1650€. Quel est son salaire après cette augmentation ?",
          "Le salaire de juillet de M Legrand s’élève à 1542€. Calculer le salaire de juin.",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Un commerçant diminue ses prix de 8%.",
          "Un lecteur DVD coûte, avant réduction, 329€. Combien coûtera-t-il après ?",
          "Un écran LCD coûte, après réduction, 540€. Combien coûtait-t-il avant ?",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "proportionnalite",
    id: "proportionnalite-6",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Proportionnalité",
    level: "Troisième",
    number: 6,
    limitDate: "",
    validationDate: "",
    statements: "Pourcentages:",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Le prix d’un lecteur CD est 180€. Il est soldé au prix de 135€.",
          "Quel est le pourcentage de réduction accordée par rapport au prix initial ?",
          "Un client désire acheter cet appareil. Il possède une carte de fidélité du magasin qui lui permet de bénéficier d’une remise de 5% en caisse. Combien paiera-t-il ce lecteur ?",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Un capital est placé à 3,5% pendant 1 an a rapporté 273€ d’intérêts.",
          "Calculer le montant de ce capital.",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "proportionnalite",
    id: "proportionnalite-7",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Proportionnalité",
    level: "Troisième",
    number: 7,
    limitDate: "",
    validationDate: "",
    statements: "Pourcentages:",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Suite à un déménagement, le loyer d’une famille baisse de 18 %. Sachant que son loyer était de 580 € par mois.",
          "Détrerminer la diminution du montant du loyer.",
          "Détrerminer le prix actuel du loyer.",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Un livre neuf vaut 60 € hors taxe. Le taux de TVA est de 19,6 %.",
          "Déterminer le montant de la TVA.",
          "En déduire le prix du livre taxe comprise.",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "trigonometrie",
    id: "trigonometrie-1",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Trigonométrie",
    level: "Troisième",
    number: 1,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Complète le tableau avec le numéro du triangle qui convient.",
        ],
        imgName: "trigonometrie-img3",
        solution: [],
      },
      {
        time: 300,
        question: [
          "À l'aide de la calculatrice, calcule les valeurs, arrondies au centième, du sinus et de la tangente des angles données.",
        ],
        imgName: "trigonometrie-img4",
        solution: [],
      },
    ],
  },
  {
    chapterName: "trigonometrie",
    id: "trigonometrie-2",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Trigonométrie",
    level: "Troisième",
    number: 2,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "ABC est un triangle rectangle en A. H est le pied de la hauteur issue de A. $AH = 5\\ cm \\ \\ et \\ \\widehat{ABC} =\\ 40^\\circ$",
          "Calculer la longueur AB arrondie au dixième. ",
        ],
        imgName: "trigonometrie-img1",
        solution: [],
      },
      {
        time: 300,
        question: [
          "",
          "Calcule la longueur PK arrondie au millimètre.",
          "Déduis-en la longueur PJ arrondie au millimètre.",
        ],
        imgName: "trigonometrie-img2",
        solution: [],
      },
    ],
  },
  {
    chapterName: "trigonometrie",
    id: "trigonometrie-3",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Trigonométrie",
    level: "Troisième",
    number: 3,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "",
          "Calculer l'angle $\\widehat{URT}$",
          "Calculer l'angle $\\widehat{UTR}$",
          "Calculer l'angle $\\widehat{RUT}$",
        ],
        imgName: "trigonometrie-img5",
        solution: [],
      },
      {
        time: 300,
        question: [
          "On considère la figure ci-dessus où les points B, C et D sont alignés.",
          "Calculer la valeur exacte de la distance BC.",
          "Calculer une valeur approchée au degré de l’angle $\\widehat{BAC}$",
          "Calculer un arrondi au millimètre près de la distance BD.",
        ],
        imgName: "trigonometrie-img6",
        solution: [],
      },
    ],
  },
  {
    chapterName: "trigonometrie",
    id: "trigonometrie-4",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Trigonométrie",
    level: "Troisième",
    number: 4,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Lors d’une intervention les pompiers doivent atteindre une fenêtre F située à 18 m du sol en utilisant la grande échelle [PF]. Ils doivent prévoir le réglage de l’échelle. Le pied P de l’échelle est situé sur le camion à 1, 5 m du sol et à 10 m de l’immeuble.",
          "Avec les informations ci-dessus, calculer RF",
          "Déterminer au degré près l’angle que fait l’échelle avec l’horizontale, c’est à dire l’angle $\\widehat{FPR}$",
          "L’échelle à une longueur maximale de 25 m. Sera-t-elle assez longue pour atteindre la fenêtre ?",
        ],
        imgName: "trigonometrie-img7",
        solution: [],
      },
      {
        time: 300,
        question: [
          "",
          "Calculer la longueur EU.",
          "Calculer la mesure (arrondie à l’unité) de l’angle $\\widehat{BEU}$.",
          "Calculer la longueur AU, arrondie au mm.",
        ],
        imgName: "trigonometrie-img8",
        solution: [],
      },
    ],
  },
  {
    chapterName: "trigonometrie",
    id: "trigonometrie-5",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Trigonométrie",
    level: "Troisième",
    number: 5,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Dans la figure ci-dessus, AB = 4 cm, AD = 5 cm et AE = 7 cm. On donnera les mesures d’angles arrondies au dixième de degré et les longueurs au dixième de centimètre.",
          "Calculer l'angle $\\widehat{BAD}$.",
          "Calculer la longueur AC.",
          "Calculer la longueur CE.",
        ],
        imgName: "trigonometrie-img9",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Dans le triangle ERN, on donne : EN = 9 cm RN = 10,6 cm $\\widehat{ENR} = 60°.$ La hauteur issue de E coupe le côté [RN] en A. La parallèle à (EN) passant par A coupe le côté [RE] en T.",
          "Calculer la distance AN",
          "Calculer EA (on arrondira au dixième de centimètre).",
          "Calculer AR. ",
          "Calculer TA (on arrondira au dixième de centimètre).",
          "Calculer l’angle (on arrondira au degré) $\\widehat{ERA}$ .",
        ],
        imgName: "trigonometrie-img10",
        solution: [],
      },
    ],
  },
  {
    chapterName: "trigonometrie",
    id: "trigonometrie-6",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Trigonométrie",
    level: "Troisième",
    number: 6,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "On considère la figure ci-dessus. Les droites (AC) et (BD) s'intercepte au point O.",
          "Déterminer la mesure de l'angle (arrondie au dixième de degré près) $\\widehat{BAO}$.",
          "En déduire la mesure de l'angle $\\widehat{COD}$",
          "Déterminer le périmètre du triangle (arrondie au millimètre près) $\\widehat{ODC}$.",
        ],
        imgName: "trigonometrie-img11",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Le dessin ci-contre représente la coupe d'une maison. Le triangle MAI est isocèle, de sommet principal M. La droite perpendiculaire à la droite (AI), passant par M , coupe (AI) en S. On sait que : MS = 2,5 et AI = 11. (L'unité de longueur est le mètre).",
          "Calculer AS.",
          "Calculer la valeur arrondie à 0,1 degré près de la mesure de l'angle $\\widehat{AMS}$",
          "Dans le toit, il y a une fuite en N qui fait une tache en O, sur le plafond. La droite (NO) est perpendiculaire à la droite (AI). AO = 4,5. Pour effectuer les calculs, on prendra : $\\widehat{OAN}$ = 24°. \\ $Calculer AN. (On donnera la valeur arrondie à 0,1 près).$",
        ],
        imgName: "trigonometrie-img12",
        solution: [],
      },
    ],
  },
  {
    chapterName: "trigonometrie",
    id: "trigonometrie-7",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Trigonométrie",
    level: "Troisième",
    number: 7,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Juliette mesure l'angle entre l'horizontale et le haut du réservoir d'un château d'eau grâce à un appareil placé à 1,70 m du sol. Elle trouve 58°.",
          "Calcule la hauteur du château d'eau arrondie au mètre.",
          "La contenance de celui-ci est de 500 m3 d'eau. Calcule le diamètre de la base en considérant que le réservoir du château d'eau est cylindrique. Arrondis au décimètre.",
        ],
        imgName: "trigonometrie-img13",
        solution: [],
      },
      {
        time: 300,
        question: [
          "On considère un cercle de centre O et de diamètre [BC] tel que BC = 8 cm. On place sur ce cercle un point A tel que BA = 4 cm.",
          "Faire une figure en vraie grandeur et démontrer que le triangle ABC est rectangle en A.",
          "Calculer la valeur exacte de la longueur AC. Donner la valeur arrondie de AC au millimètre près.",
          "Déterminer la mesure de l’angle $\\widehat{ABC}$.",
        ],
        imgName: "",
        graph: true,
        solution: [],
      },
    ],
  },
  {
    chapterName: "transformations-du-plan",
    id: "transformations-du-plan-1",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Transformation du plan",
    level: "Troisième",
    number: 1,
    limitDate: "",
    validationDate: "",
    statements:
      "Construis les parallélogrammes ABCD, EFGH et IJKL de centre M respectant les conditions suivantes :",
    questionsSolutions: [
      {
        time: 300,
        question: ["1) AB = 5 cm, AD = 3,5 cm et BD = 7 cm."],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["2) EF = 2 cm, EH = 4,5 cm et EG = 3,5 cm."],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["3) IJ = 6 cm, JM = 5 cm et IM = 4 cm."],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "transformations-du-plan",
    id: "transformations-du-plan-2",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Transformation du plan",
    level: "Troisième",
    number: 2,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Pour chaque énoncé, trace une figure à main levée.",
          "1) Le quadrilatère NOIR est un parallélogramme tel que RN = 4 cm. Donne la longueur OI. ",
          "2) Le quadrilatère BLEU est un parallélogramme de centre S tel que sa diagonale [BE] a pour longueur 8 cm. Donne la longueur BS.",
          "3) Le quadrilatère VERT est un parallélogramme tel que l'angle $\\widehat{VER}$ $ a pour mesure 53°. Quelle est la mesure de l'angle$ $\\widehat{VTR}$ ?",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Construis en vraie grandeur les rectangles dessinés ci-dessus à main levée en respectant les mesures indiquées sur les figures. (Les longueurs sont données en centimètres.)",
        ],
        imgName: "transformations-img22",
        solution: [],
      },
    ],
  },
  {
    chapterName: "transformations-du-plan",
    id: "transformations-du-plan-3",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Transformation du plan",
    level: "Troisième",
    number: 3,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "",
          "Pour la figure, lequel des points M1, M2 ou M3 semble être le symétrique de M par rapport à (d) ?",
        ],
        imgName: "transformations-img31",
        solution: ["3"],
        radio: true,
        options: [
          { label: "M1", value: "1" },
          { label: "M2", value: "2" },
          { label: "M3", value: "3" },
        ],
      },
      {
        time: 300,
        question: [
          "",
          "Pour la figure, lequel des points M1, M2 ou M3 semble être le symétrique de M par rapport à (d) ?",
        ],
        imgName: "transformations-img32",
        solution: ["2"],
        radio: true,
        options: [
          { label: "M1", value: "1" },
          { label: "M2", value: "2" },
          { label: "M3", value: "3" },
        ],
      },
      {
        time: 300,
        question: [
          "",
          "Pour la figure, lequel des points M1, M2 ou M3 semble être le symétrique de M par rapport à (d) ?",
        ],
        imgName: "transformations-img33",
        solution: ["2"],
        radio: true,
        options: [
          { label: "M1", value: "1" },
          { label: "M2", value: "2" },
          { label: "M3", value: "3" },
        ],
      },
    ],
  },
  {
    chapterName: "transformations-du-plan",
    id: "transformations-du-plan-4",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Transformation du plan",
    level: "Troisième",
    number: 4,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "La figure ci-dessus est composée de triangles équilatéraux.",
          "1. Quelle est l’image de B par la rotation de centre K, d’angle 60° dans le sens horaire ?",
          " 2. Quelle est l’image de D par la rotation de centre B, d’angle 120° dans le sens horaire ?",
          "3. Quelle est l’image de I par la rotation de centre B, d’angle 60° dans le sens antihoraire ?",
          "4. Quelle est l’image de L par la rotation de centre K, d’angle 60° dans le sens horaire ?",
        ],
        imgName: "transformations-img41",
        solution: [],
      },
      {
        time: 300,
        question: [
          "La figure ci-dessus est composée de triangles équilatéraux.",
          "1. Quelle est l’image de J par la rotation de centre E, d’angle 120° dans le sens antihoraire ?",
          "2. Quelle est l’image de I par la rotation de centre J, d’angle 180° dans le sens horaire ?",
          "3. Quelle est l’image de C par la rotation de centre E, d’angle 240° dans le sens horaire ?",
          "4. Quelle est l’image de K par la rotation de centre J, d’angle 240° dans le sens antihoraire ? ",
        ],
        imgName: "transformations-img41",
        solution: [],
      },
    ],
  },
  {
    chapterName: "transformations-du-plan",
    id: "transformations-du-plan-5",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Transformation du plan",
    level: "Troisième",
    number: 5,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Le quadrilatère ROSE est un losange de centre T. RO = 9,1 cm, $\\widehat{ORE}$ = 50°.",
          "Calcule son périmètre P",
          "Calculer l'angle $\\widehat{ORS}$",
          "Calculer l'angle $\\widehat{OSE}$",
        ],
        imgName: "transformations-img51",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Pour chacun des cas suivants, indique l'angle et le sens de la rotation de centre C qui transforme A en B.",
          "ABC est un triangle rectangle isocèle en C.",
          "ABC est un triangle isocèle en C tel que $\\widehat{A}$= 70°.",
          "ABC est un triangle équilatéral.",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "transformations-du-plan",
    id: "transformations-du-plan-6",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Transformation du plan",
    level: "Troisième",
    number: 6,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "À partir de la figure ci-dessus :",
          "Par la translation qui transforme D en C, quelle est l'image du point B ? ",
          "Par la translation qui transforme D en C, quelle est l'image du point G ? ",
          "Par la translation qui transforme D en C, quelle est l'image du point A ? ",
          "Par la translation qui transforme D en G, quelle est l'image du point C ?",
        ],
        imgName: "transformations-img61",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Construire les points A’, B’, C’, D’ et E’, symétriques respectifs de A, B, C, D et E par rapport au centre O.",
        ],
        imgName: "transformations-img62",
        solution: [],
      },
    ],
  },
  {
    chapterName: "transformations-du-plan",
    id: "transformations-du-plan-7",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Transformation du plan",
    level: "Troisième",
    number: 7,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Construire la symétrique de la figure par rapport à la droite (d1) puis par rapport à la droite (d2).",
        ],
        imgName: "transformations-img71",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Construire la symétrique de la figure par rapport au point O1 puis par rapport au point O2.",
        ],
        imgName: "transformations-img72",
        solution: [],
      },
    ],
  },
  {
    chapterName: "probabilites",
    id: "probabilites-1",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Probabilités",
    level: "Troisième",
    number: 1,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "On lance un pièce truquée. La probabilité d’obtenir « face » est 0,35.",
          "Quelle est la probabilité d’obtenir « pile » ?",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Dans un sac contenant des lettres de l’alphabet, on en tire une au hasard. La probabilité que ce soit une consonne est $\\frac{5}{7}$.",
          "Quelle est la probabilité de tirer une voyelle ?",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "On lance deux dé à six faces et on calcule la somme des nombres inscrits sur leur face supérieure.",
          "Citer les issues de cette expérience. (Séparer vos réponses avec des points-virgules).",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Pour un tirage au hasard, on a placé dans une urne 25 boules de même taille, les unes blanches, les autres noires. La probabilité de tirer une boule blanche est 0,32.",
          "Quelles sont les boules les plus nombreuses dans l'urne : les blanches ou les noires ?",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "probabilites",
    id: "probabilites-2",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Probabilités",
    level: "Troisième",
    number: 2,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Avec la roue ci-dessus :",
          "Quelle est la probabilité : que le numéro obtenu soit un nombre pair ?",
          "Quelle est la probabilité : que le numéro obtenu soit divisible par 3 ?",
          "Quelle est la probabilité : que le numéro obtenu soit un nombre premier ?",
        ],
        imgName: "probabilites-img11",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Un jeu de 32 cartes est constitué du 1 (as), 7, 8, 9, 10, valet, dame, roi ceci dans les 4 couleurs : coeur, carreau, pique, trèfle. On tire au hasard une carte dans ce jeu.",
          "1. Quelle est la probabilité de l'événement A : `Tirer la reine de coeur` ?",
          "2. Quelle est la probabilité de l'événement B : `Tirer un trèfle` ?",
          "3. Quelle est la probabilité de l'événement C : `Tirer un as` ?",
          "4. Quelle est la probabilité de l'événement D : `Tirer un as de couleur rouge` ?",
          "5. Quelle est la probabilité de l'événement E : `Tirer une carte de couleur noire` ?",
          "6. Quelle est la probabilité de l'événement F : `Tirer une carte de couleur noire ou rouge` ?",
          "7. Quelle est la probabilité de l'événement G : `Tirer une carte de couleur noire et rouge` ?",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "probabilites",
    id: "probabilites-3",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Probabilités",
    level: "Troisième",
    number: 3,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "On tire au hasard une carte d’un jeu de 32 cartes, on la note, puis on la remet dans le jeu avant d’en tirer une seconde.",
          "1) Est-ce une situation d’équiprobabilité ?",
          "2) Combien y a-t-il d’issues ?",
          "3)a) Calculer la probabilité de : tirer 2 cœurs.",
          "3)b) Calculer la probabilité de : ne pas tirer de cœur.",
          "3)c) Calculer la probabilité de : tirer exactement 1 cœur.",
          "3)d) Calculer la probabilité de : tirer deux fois la même carte.",
          "3)e) Calculer la probabilité de : tirer deux cartes différentes.",
          "3)f) Calculer la probabilité de : tirer le roi de cœur.",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "On tire au hasard deux cartes d’un jeu de 32 cartes, l’une après l’autre.",
          "1) Est-ce une situation d’équiprobabilité ?",
          "2) Combien y a-t-il d’issues ?",
          "3)a) Calculer la probabilité de : tirer 2 cœurs.",
          "3)b) Calculer la probabilité de : tirer exactement 1 cœur.",
          "3)c) Calculer la probabilité de : tirer deux fois la même carte.",
          "3)d) Calculer la probabilité de : tirer deux cartes différentes.",
          "3)e) Calculer la probabilité de : tirer le roi de cœur.",
          "4) Calculer la probabilité de ne pas tirer de cœur.",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "probabilites",
    id: "probabilites-4",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Probabilités",
    level: "Troisième",
    number: 4,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "On lance un dé pipé à 6 faces. Le tableau ci-dessus regroupe les probabilités.",
          "1) Calculer p(6).",
          "2)a) Calculer la probabilités de l'événement: « La face obtenue est paire ».",
          "2)a) Calculer la probabilités de l'événement: « la face obtenue est supérieur ou égale à 5 ».",
        ],
        imgName: "probabilites-img41",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Deux dés tétraédriques ont des faces numérotées de 1 à 4. On les lance et on regarde la somme obtenue.",
          "1) Quels sont les résultats possibles ? (Séparer vos réponses avec des points-virgules).",
          "2) Est-ce une situation d’équiprobabilité ?",
          "3) Déterminer la probabilité de chaque résultat. (Séparer vos réponses avec des points-virgules).",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "probabilites",
    id: "probabilites-5",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Probabilités",
    level: "Troisième",
    number: 5,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "On dispose d’un sac qui contient 6 boules : 4 boules vertes et 2 boules jaunes. Les boules vertes sont numérotées 1 ; 2 ; 2 ; 3 et les boules jaunes 1 et 2. On tire une boule au hasard et on note sa couleur et son numéro. ",
          "Calculer la probabilité de l'évènement suivant : « Tirer une boule jaune ».",
          "Calculer la probabilité de l'évènement suivant : « Tirer une boule portant le numéro 2 ».",
          "Calculer la probabilité de l'évènement suivant : « Tirer une boule verte portant le numéro 2 ».",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Un sachet contient 2 bonbons à la menthe, 3 à l’orange et 5 au citron. On tire, au hasard, un bonbon du sachet et on définit les évènements : A : « le bonbon est à la menthe », B : « le bonbon est à l’orange », C : « le bonbon est au citron ». ",
          "1) Quel est le nombre d’issues possibles ? ",
          "2) Déterminer la probabilité p(A). ",
          "3) Déterminer la probabilité p(B). ",
          "4) Déterminer la probabilité p(C). ",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "probabilites",
    id: "probabilites-6",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Probabilités",
    level: "Troisième",
    number: 6,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Une urne contient 5 boules rouges dont 2 ont une tache noire et 4 boules jaunes dont une a une tache noire. On extrait une boule au hasard.",
          "Quelle est la probabilité de A : « la boule extraite est jaune ».",
          "Quelle est la probabilité de B : « la boule extraite a une tache noire ». ",
          "Quelle est la probabilité de C : « la boule extraite n’est pas jaune et sans tache noire ».",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Quand Jean tire à l’arc, il atteint sa cible 9 fois sur 10. Jean se présente pour tirer une flèche. On note T l’événement « Jean atteint sa cible ». ",
          "Quelle est la probabilité P(T) ?",
          "Calculer P(non T). ",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "probabilites",
    id: "probabilites-7",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Probabilités",
    level: "Troisième",
    number: 7,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Dans un sac, on a placé 3 jetons numérotés 3 ; 4 ; 5. On tire au hasard, successivement et sans les remettre dans le sac tous les jetons du sac. On écrit le nombre qui a comme chiffre des centaines le 1er nombre tiré, comme chiffre des dizaines le 2ème nombre tiré et comme chiffre des unités le 3ème nombre tiré. ",
          "a / Si on tire le 3 puis le 5 et enfin le 4 quel nombre obtient-on ?",
          "b / A l’aide d’un arbre, établir tous les résultats possibles.",
          "c / Quelle la probabilité de l’événement : « obtenir 453 » ?",
          "d / Quelle est la probabilité de l’événement : « obtenir un nombre inférieur à 453 » ?",
          "e / Quelle est la probabilité de l’événement : « obtenir un nombre multiple de 3 » ? Pouvaiton prévoir le résultat ?",
          "f / Quelle est la probabilité de l’événement : « obtenir un nombre multiple de 2 » ? ",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "statistiques",
    id: "statistiques-1",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Statistiques",
    level: "Troisième",
    number: 1,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Voici un diagramme représentant le nombre de prospectus publicitaires reçus par un habitant de Lille chaque mois de l'année 2019.",
          "Calcule le nombre moyen de publicités reçues par mois durant l'année 2019.",
        ],
        imgName: "statistiques-img11",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Dans un groupe de personnes, on considère le nombre de frères et sœurs de chacun. On relève les données statistiques dans le tableau ci-dessus :",
          "a. Donne l'effectif total de cette série.",
          "b. Combien de personnes ont quatre frères et sœurs ?",
          "c. Combien de personnes ont au moins trois frères et sœurs ?",
          "d. Calcule le nombre moyen de frères et sœurs.",
        ],
        imgName: "statistiques-img12",
        solution: [],
      },
    ],
  },
  {
    chapterName: "statistiques",
    id: "statistiques-2",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Statistiques",
    level: "Troisième",
    number: 2,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Ce tableau compare les températures mensuelles moyennes (en °C) au cours d'une année dans deux villes Alpha (A) et Gamma (G). Pour la ville Alpha, puis pour la ville Gamma, calcule :",
          "a. la moyenne des températures.",
          "b. une médiane des températures.",
          "c. l'étendue des températures.",
        ],
        imgName: "statistiques-img13",
        solution: [],
      },
      {
        time: 300,
        question: [
          "On a relevé les performances, en mètres, obtenues par les élèves d'une classe au lancer du poids. 3,45 | 5,2 | 5,35 | 4,3 | 6,1 | 4,28 | 5,18 | 4,9 | 6,21 | 5,36 | 5,22 | 4,9 | 3,95 | 4,72 | 5,5 | 6,13 | 5,6 | 4,19 | 4,75 | 5,04 | 4,88 | 5,6 | 6,04 | 5,43.",
          "a. Quel est l'effectif total de cette série ?",
          "b. Range les données dans l'ordre croissant puis détermine une médiane de cette série.",
          "c. Quelle est l'étendue de cette série ?",
          "d. Quel est le pourcentage des performances inférieures à 5 m ?",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "statistiques",
    id: "statistiques-3",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Statistiques",
    level: "Troisième",
    number: 3,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Voici le classement général des sept premiers coureurs à l'issue de la 21° étape du tour de France 2015. On considère la série statistique des temps de course.",
          "1. Calculer la différence entre les temps de course de Bauke Mollema et de Christopher Froome.",
          "2. Que représente pour la série statistique la différence calculée à la question 1 ?",
          "3. Quelle est la médiane de cette série ?",
        ],
        imgName: "statistiques-img31",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Le tableau ci-dessous présente l’évolution des températures minimales $(T_{min})$ et maximales $(T_{max})$ observées en différents lieux de Nouvelle-Calédonie au cours des 40 dernières années.",
          "a. Ce tableau traduit-il une augmentation ou une diminution des températures ? Expliquer.",
          "b. En quel lieu la température minimale a-t-elle le plus augmenté ?",
          "c. Calculer l’augmentation moyenne des températures minimales et celle des températures maximales depuis 40 ans.",
        ],
        imgName: "statistiques-img32",
        solution: [],
      },
    ],
  },
  {
    chapterName: "statistiques",
    id: "statistiques-4",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Statistiques",
    level: "Troisième",
    number: 4,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Deux classes d’un collège ont répondu à la question suivante : « Combien de livres avez-vous empruntés au CDI durant les 12 derniers mois ? ». Les deux classes ont communiqué leurs réponses de deux façons différentes dans le tableau ci-dessus.",
          "a. Comparer les nombres moyens de livres empruntés dans chaque classe (répondre avec le nombre moyen le plus grand).",
          "b. Un « grand lecteur » est un élève qui a emprunté 5 livres ou plus. Quelle classe a le plus de « grands lecteurs » ?",
          "c. Dans quelle classe se trouve l’élève ayant emprunté le plus de livres ? ",
        ],
        imgName: "statistiques-img41",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Voici ci-dessus les effectifs et les salaires des employés d’une Petite et Moyenne Entreprise (PME).",
          "1. Quel est l’effectif de cette PME?",
          "2. Calculer le salaire moyen arrondi à l’unité.",
          "3. Déterminer l’étendue des salaires.",
          "4. Les dirigeants décident une augmentation de 8 % du montant du salaire d’un ouvrier simple. Calculer le nouveau salaire de cet ouvrier.",
        ],
        imgName: "statistiques-img42",
        solution: [],
      },
    ],
  },
  {
    chapterName: "statistiques",
    id: "statistiques-5",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Statistiques",
    level: "Troisième",
    number: 5,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Sur cette feuille de calcul ci-dessus, on a reporté le classement des dix premiers pays, par le nombre de médailles, aux Jeux Olympiques de Rio en 2016. On observe la série des nombres de médailles d’or de ces dix pays.",
          "1a. Quelle est l’étendue de cette série?",
          "1b Quelle est la moyenne de cette série?",
          "2. Quel est le pourcentage de médailles d’or remportées par la France par rapport à son nombre total de médailles? Arrondir le résultat en pourcentage au dixième près.",
          "3. Le classement aux Jeux Olympiques s’établit selon le nombre de médailles d’or obtenues et non selon le nombre total de médailles. Pour cette raison, la France avec 42 médailles se retrouve derrière le Japon qui n’en a que 41. En observant l’Italie et l’Australie, établir la règle de classement en cas d’égalité sur le nombre de médailles d’or (si l'Italie est devant répondre : Italie, si le japon est devant répondre : Japon).",
          "4. Un journaliste sportif propose une nouvelle procédure pour classer les pays : chaque médaille d’or rapporte 3 points, chaque médaille d’argent rapporte 2 points et chaque médaille de bronze rapporte 1 point. Dans ces conditions, la France dépasserait-elle le Japon?",
        ],
        imgName: "statistiques-img51",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Le diagramme en barres cidessous donne la répartition des notes obtenues à un contrôle de mathématiques par les élèves d’une classe de 3ème.",
          "1. Combien d’élèves y a-t-il dans cette classe?",
          "2. Quelle est la note moyenne de la classe à ce contrôle?",
          "3. Quelle est la note médiane?",
          "4. Quelle est l’étendue de cette série de notes?",
          "5. Détermine la valeur du premier quartile de cette série de notes.",
          "6. Détermine la valeur de la troisième quartile de cette série de notes.",
        ],

        imgName: "statistiques-img52",
        solution: [],
      },
    ],
  },
  {
    chapterName: "geometrie-dans-lespace",
    id: "geometrie-dans-lespace-1",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Géometrie dans l'espace",
    level: "Troisième",
    number: 1,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "On considère le cube ABCDEF GH représenté ci-dessus.",
          "Déterminer la nature du quadrilatère DBFH.",
        ],
        imgName: "geometrie-dans-lespace-3-img-11",
        solution: [],
      },
      {
        time: 300,
        question: [
          "On considère la pyramide ABCDS de sommet S et dont la base est rectangulaire. On coupe ce solide par un plan (P) parallèle à la base. On obtient la section EFGH.",
          "1. Quelle est la nature de la section EFGH ?",
          "2. Quelle est la nature du solide EFGHS ?",
        ],
        imgName: "geometrie-dans-lespace-3-img-12",
        solution: [],
      },
    ],
  },
  {
    chapterName: "geometrie-dans-lespace",
    id: "geometrie-dans-lespace-2",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Géometrie dans l'espace",
    level: "Troisième",
    number: 2,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "",
          "Dans la figure 1, la section est effectuée par un plan parallèle à la base du cône de révolution. Quelle est la nature de la section?",
          "Dans la figure 2, la section est effectuée par un plan perpendiculaire à la base du cône de révolution et passant par le sommet du cône. Quelle est la nature de la section?",
        ],
        imgName: "geometrie-dans-lespace-3-img-21",
        solution: [],
      },
      {
        time: 300,
        question: [
          "On considère le parallélépipède ABCDEF GH ayant pour dimensions : AB = 6cm ; BC = 3 cm BF = 2 cm. Un plan parallèle à l’arête [F G] intercepte le parallélépipède formant pour section le quadrilatère IJKL où : AI = 3 cm ; KG = 2 cm",
          "1. Quelle est la nature du quadrilatère ?",
          "2a. Déterminer la mesure, arrondie au millimètre près, de la longueur IL.",
          "2b. Déterminer l’aire du quadrilatère IJKL arrondie au centimètre carrée près.",
        ],
        imgName: "geometrie-dans-lespace-3-img-22",
        solution: [],
      },
    ],
  },
  {
    chapterName: "geometrie-dans-lespace",
    id: "geometrie-dans-lespace-3",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Géometrie dans l'espace",
    level: "Troisième",
    number: 3,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Un aquarium a la forme d’une calotte sphérique obtenue en coupant une sphère de centre O et de rayon 13 cm par un plan. La hauteur HS de l’aquarium est 25 cm.",
          "1. Quelle est la nature de l’ouverture de l’aquarium ?",
          "2. Sachant que les points H, O et S sont alignés, calculer la longueur HM.",
        ],
        imgName: "geometrie-dans-lespace-3-img-31",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Un astronome vient de découvrir deux planètes, Magnus et Minus, chacune des deux étant assimilée à une sphère. On sait que le rayon de Magnus est de 2 832 km.",
          "a. Calcule le volume de Magnus au kilomètre cube près.",
          "b. Le volume de la planète Minus vaut exactement $\\frac{1}{8}$ $de celui de la planète Magnus. Détermine le rayon de la planète Minus.$",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "geometrie-dans-lespace",
    id: "geometrie-dans-lespace-4",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Géometrie dans l'espace",
    level: "Troisième",
    number: 4,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "SABCD est une pyramide dont la base est le rectangle ABCD. On place sur sa hauteur [SA] le point A’ tel que SA’ = 6 cm. En coupant la pyramide SABCD par un plan parallèle à sa base, on obtient une pyramide réduite SA’B’C’D’.On donne : SA = 9 cm AB = 8 cm BC = 6 cm. ",
          "1. Calculer le rapport de réduction",
          "2.a. Calculer l’aire du rectangle ABCD.",
          "2.b. En déduire l’aire du quadrilatère A’B’C’D’.",
          "3.a. Calculer le volume de la pyramide SABCD.",
          "3.b. En déduire le volume de la pyramide SA’B’C’D’.",
        ],
        imgName: "geometrie-dans-lespace-3-img-41",
        solution: [],
      },
      {
        time: 300,
        question: [
          "On considère un cône de sommet S et dont la base est un disque de rayon [OM]. M’ est un point du segment [SM]. On donne : SO = 4,8 cm OM = 2 cm SM’ = 3,9 cm. On coupe ce cône par un plan passant par le point M’ et parallèle à sa base. On obtient un cône (C), réduction du cône initial.",
          "1. Calculer la longueur SM",
          "2. Calculer le volume du cône, donner la valeur arrondie au mm3 près.",
          "3a. Exprimer le rapport de réduction sous forme de fraction irréductible.",
          "3b. Calculer la valeur exacte du volume du cône (C), donner la valeur arrondie au mm3 près.",
        ],
        imgName: "geometrie-dans-lespace-3-img-42",
        solution: [],
      },
    ],
  },
  {
    chapterName: "geometrie-dans-lespace",
    id: "geometrie-dans-lespace-5",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Géometrie dans l'espace",
    level: "Troisième",
    number: 5,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Le Soleil est assimilé à une boule de 1 392 000 km de diamètre.",
          "a. Calcule la surface du Soleil. (Arrondir à l'unité)",
          "b. Calcule le volume du Soleil. (Arrondir à l'unité)",
          "c. Sachant que la Terre a un rayon de 6 378 km, calcule son volume.(Arrondir à l'unité)",
          "d. De combien de fois le Soleil est-il plus volumineux que la Terre ?",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "On assimile la Terre à une sphère de rayon 6 378 km. L'équateur et les méridiens sont des grands cercles de cette sphère.",
          "a. Calcule la longueur de l'équateur.",
          "b. Quelle est la distance entre le pôle Nord et le pôle Sud ?",
          "c. L'aventurier Kévin Fog a réédité l'exploit de son arrière-grand-père : le tour du monde en quatre-vingts jours en survolant l'équateur à une hauteur de 1 000 m. Quelle a été sa vitesse moyenne en km/h ?",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "geometrie-dans-lespace",
    id: "geometrie-dans-lespace-6",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Géometrie dans l'espace",
    level: "Troisième",
    number: 6,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Un jouet a la forme d’une demi boule surmontée d’un cône de révolution de sommet A, comme l’indique la figure ci–dessus. Le segment [BC] est un diamètre de la base du cône ; le point O est le centre de cette base. On donne AB = 7cm et BC = 6cm.",
          "Calculer le volume de ce jouet, cône et demi-boule réunis (on donnera le résultat arrondi au cm3 près).",
        ],
        imgName: "geometrie-dans-lespace-3-img-61",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Un médicament a la forme ci-dessus. On sait que OP = 5mm et ON = 2mm.",
          "Calculer le volume de ce médicament (on donnera la valeur arrondie au mm3 près).",
        ],
        imgName: "geometrie-dans-lespace-3-img-62",
        solution: [],
      },
    ],
  },
];
