export const exercisesTroisieme = [
  {
    chapterName: "calcul-litteral",
    id: "troisieme-calcul-litteral-1",
    isCompleted: false,
    scoreAverage: 0,
    level: "Troisième",
    lesson: "Calcul Littéral",
    number: 1,
    limitDate: "",
    validationDate: "",
    statements: "Développer, réduire et ordonner les expressions suivantes :",
    questionsSolutions: [
      {
        time: 3,
        question: ["", "$\\mathrm{A}=3(4x+7)+4(2x-9)$"],
        imgName: "",
        solution: [
          "$\\mathrm{A}= 3 × 4x + 3 × 7 + 4 × 2x + 4 × (-9)$",
          "$\\mathrm{A}= 12x + 21 + 8x - 36$",
          "$\\mathrm{A}= 20x - 15$",
        ],
      },
      {
        time: 3,
        question: ["", "$\\mathrm{B}=7x(2x-5)-x(2x-5)$"],
        imgName: "",
        solution: [
          "$\\mathrm{B}=7x × 2x + 7x × (-5) -x × 2x -x × (-5)$",
          "$\\mathrm{B}= 14x^2 - 35x -2x^2 + 5x$",
          "$\\mathrm{B}= 12x^2 - 30x$",
        ],
      },
      {
        time: 300,
        question: ["", "$\\mathrm{C}=(2x+5)(3x+7)$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$\\mathrm{D}=(2x-5)(3x-2)$"],
        imgName: "",
        solution: [],
      },
    ],
  },

  {
    chapterName: "calcul-litteral",
    id: "troisieme-calcul-litteral-2",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Calcul Littéral",
    level: "Troisième",
    number: 2,
    limitDate: "",
    validationDate: "",
    statements: "Développer, réduire et ordonner les expressions suivantes :",
    questionsSolutions: [
      {
        time: 300,
        question: ["", "$\\mathrm{E}=(2 x+3)(5 x-8)-(2 x-4)(5 x-1)$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$\\mathrm{F}=(5 x-2)(5 x-8)-(3 x-5)(x+7)$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$\\mathrm{G}=2(x+7)(3-2 x)+(5 x-2)(4 x+1)$"],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "calcul-litteral",
    id: "troisieme-calcul-litteral-3",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Calcul Littéral",
    level: "Troisième",
    number: 3,
    limitDate: "",
    validationDate: "",
    statements:
      "Développer, réduire et ordonner les expressions suivantes sans étape de calcul :",
    questionsSolutions: [
      {
        time: 300,
        question: ["", "$\\mathrm{H}=(x+5)^{2}$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$\\mathrm{I}=(4 x+6)^{2}$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$\\mathrm{J}=(x-5)^{2}$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$\\mathrm{K}=(3 x-7)^{2}$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$\\mathrm{L}=(y+3)(y-3)$"],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "calcul-litteral",
    id: "troisieme-calcul-litteral-4",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Calcul Littéral",
    level: "Troisième",
    number: 4,
    limitDate: "",
    validationDate: "",
    statements: "Développer, réduire et ordonner les expressions suivantes :",
    questionsSolutions: [
      {
        time: 300,
        question: ["", "$\\mathrm{N}=\\left(3 x-\\frac{2}{3}\\right)^{2}$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "",
          "$\\mathrm{P}=\\left(\\frac{5}{2}+\\frac{1}{3} x\\right)\\left(\\frac{1}{3} x-\\frac{5}{2}\\right)$",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$\\mathrm{Q}=(x+2)^{2}-6(3 x-5)^{2}$"],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "calcul-litteral",
    id: "troisieme-calcul-litteral-5",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Calcul Littéral",
    level: "Troisième",
    number: 5,
    limitDate: "",
    validationDate: "",
    statements: "Compléter les expressions suivantes :",
    questionsSolutions: [
      {
        time: 300,
        question: ["", "$\\quad( \\ldots-\\ldots)^{2}=16 x^{2}-72 x+\\ldots$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$(5 x- \\ldots)^{2}=\\ldots-\\ldots+36$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$(\\ldots+\\ldots)^{2}=\\ldots+70 x+25$"],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "calcul-litteral",
    id: "troisieme-calcul-litteral-6",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Calcul Littéral",
    level: "Troisième",
    number: 6,
    limitDate: "",
    validationDate: "",
    statements: "Factoriser les expressions suivantes :",
    questionsSolutions: [
      {
        time: 300,
        question: ["", "$\\mathrm{A}=(x+2)(2 x-1)+(x+2)(3 x+2)$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$\\mathrm{B}=(3 x+7)(2 x-9)-(3 x+7)(5 x-7)$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$\\mathrm{C}=(8 y+3)(5 y+7)-3(8 y+3)(2 y-1)$"],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "calcul-litteral",
    id: "troisieme-calcul-litteral-7",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Calcul Littéral",
    level: "Troisième",
    number: 7,
    limitDate: "",
    validationDate: "",
    statements: "Factoriser les expressions suivantes :",
    questionsSolutions: [
      {
        time: 300,
        question: ["", "$\\mathrm{D}=(2 x+3)^{2}+(x-2)(2 x+3)$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$\\mathrm{E}=(2 t-7)-(5 t+1)(2 t-7)$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$\\mathrm{G}=(2 t-5)^{2}+(2 t-5)(x-1)+2 t-5$"],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "calcul-litteral",
    id: "troisieme-calcul-litteral-8",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Calcul Littéral",
    level: "Troisième",
    number: 8,
    limitDate: "",
    validationDate: "",
    statements: "Résoudre les équations suivantes :",
    questionsSolutions: [
      {
        time: 300,
        question: ["", "$\\quad-2(2 x-4)=6 x-(-3+x)$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$4 x-2+(5 x-1)=-3(7-x)$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$\\frac{x+5}{2}-\\frac{2 x-7}{5}=2+\\frac{3 x}{10}$"],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "calcul-litteral",
    id: "troisieme-calcul-litteral-9",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Calcul Littéral",
    level: "Troisième",
    number: 9,
    limitDate: "",
    validationDate: "",
    statements: "Résoudre les équations suivantes :",
    questionsSolutions: [
      {
        time: 300,
        question: ["", "$4(2+3 x)-(x-5)=0$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$50 x^{2}=8$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$4 x^{2}+4 x=-1$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "$\\quad(9 x-4)(-2+5 x)-(9 x-4)(3 x-5)=0$"],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "calcul-litteral",
    id: "troisieme-calcul-litteral-10",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Calcul Littéral",
    level: "Troisième",
    number: 10,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "",
          "Factoriser $\\ 4 x^{2}-12x+9.$",
          "Factoriser $\\ (2 x-3)^{2}-4.$",
          "En déduire une factorisation de $\\ 4 x^{2}-12 x+5.$",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "arithmetique",
    id: "troisieme-arithmetique-1",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Arithmétique",
    level: "Troisième",
    number: 1,
    limitDate: "",
    validationDate: "",
    statements: "Diviseurs, multiples, critères de divisibilité.",
    questionsSolutions: [
      {
        time: 300,
        question: ["", "Effectuer la division euclidienne de : 31 par 4"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "Effectuer la division euclidienne de : 79 par 9"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "Effectuer la division euclidienne de : 84 par 7"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "Effectuer la division euclidienne de : 3 par 5"],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "arithmetique",
    id: "troisieme-arithmetique-2",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Arithmétique",
    level: "Troisième",
    number: 2,
    limitDate: "",
    validationDate: "",
    statements: "Diviseurs, multiples, critères de divisibilité.",
    questionsSolutions: [
      {
        time: 300,
        question: ["", "Donner cinq multiples du nombre : 8"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "Donner cinq multiples du nombre : 11"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "Donner cinq multiples du nombre : 12"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "Donner cinq multiples du nombre : 15"],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "arithmetique",
    id: "troisieme-arithmetique-3",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Arithmétique",
    level: "Troisième",
    number: 3,
    limitDate: "",
    validationDate: "",
    statements: "Diviseurs, multiples, critères de divisibilité.",
    questionsSolutions: [
      {
        time: 300,
        question: ["", "Citer tous les diviseurs du nombre : 6"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "Citer tous les diviseurs du nombre : 17"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "Citer tous les diviseurs du nombre : 25"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "Citer tous les diviseurs du nombre : 35"],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "arithmetique",
    id: "troisieme-arithmetique-4",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Arithmétique",
    level: "Troisième",
    number: 4,
    limitDate: "",
    validationDate: "",
    statements: "Diviseurs, multiples, critères de divisibilité.",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Je suis un nombre entier compris entre 100 et 400. Je suis pair. Je suis divisible par 11. J’ai aussi 3 et 5 comme diviseurs.",
          "Qui suis-je ?",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Un livreur range 752 DVD dans des caisses qui peuvent en contenir 40.",
          "Combien faut-il de caisses pour ranger tous les DVD ? ",
          "Combien de DVD contiendra la caisse non pleine ?",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "6 798 supporters d’un club de rugby doivent faire un déplacement en car pour soutenir leur équipe. Chaque car dispose de 55 places.",
          "Combien de cars faut-il réserver ?",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "arithmetique",
    id: "troisieme-arithmetique-5",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Arithmétique",
    level: "Troisième",
    number: 5,
    limitDate: "",
    validationDate: "",
    statements: "Nombres premiers et fractions irréductibles.",
    questionsSolutions: [
      {
        time: 300,
        question: ["", "Rendre irréductible : $\\frac{55}{15}$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "Rendre irréductible : $\\frac{14}{16}$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "Rendre irréductible : $\\frac{270}{120}$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "Rendre irréductible : $\\frac{14}{49}$"],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "arithmetique",
    id: "troisieme-arithmetique-6",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Arithmétique",
    level: "Troisième",
    number: 6,
    limitDate: "",
    validationDate: "",
    statements: "Nombres premiers et fractions irréductibles.",
    questionsSolutions: [
      {
        time: 300,
        question: ["", "Écrire trois diviseurs de 12."],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "Écrire quatre diviseurs de 18."],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "Écrire quatre diviseurs de 75."],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "Écrire trois diviseurs de 64."],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "arithmetique",
    id: "troisieme-arithmetique-7",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Arithmétique",
    level: "Troisième",
    number: 7,
    limitDate: "",
    validationDate: "",
    statements: "Nombres premiers et fractions irréductibles.",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "",
          "Décomposer 25 en produits de facteurs premiers.",
          "Décomposer 125 en produits de facteurs premiers.",
          "Décomposer 456 en produits de facteurs premiers.",
          "Décomposer 2018 en produits de facteurs premiers.",
          "Rendre irréductible la fraction : $\\frac{25}{125}$ ",
          "Rendre irréductible la fraction : $\\frac{2018}{456}$",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "arithmetique",
    id: "troisieme-arithmetique-8",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Arithmétique",
    level: "Troisième",
    number: 8,
    limitDate: "",
    validationDate: "",
    statements:
      "Rendre irréductible les fractions suivantes en décomposant leur numérateur et dénominateur en produit de facteurs premiers :",
    questionsSolutions: [
      {
        time: 300,
        question: ["", "A = $\\frac{128}{244}$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "B = $\\frac{1404}{3 465}$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "C = $\\frac{408}{578}$"],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: ["", "D = $\\frac{845}{1 235}$"],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "arithmetique",
    id: "troisieme-arithmetique-9",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Arithmétique",
    level: "Troisième",
    number: 9,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "",
          " Rendre irréductible la fraction $\\frac{425}{100}$",
          "puis calculer A =$\\frac{425}{100} - \\frac{3}{2}$",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Flavien veut répartir 760 dragées au chocolat et 1 045 dragées aux amandes dans des sachets ayant la même répartition de dragées au chocolat et aux amandes.",
          "Peut-il faire 76 sachets ? Justifier.",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "arithmetique",
    id: "troisieme-arithmetique-10",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Arithmétique",
    level: "Troisième",
    number: 10,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Une ouvrière dispose de plaques de métal de 110 cm de longueur et de 88 cm de largeur. Elle a reçu la consigne suivante : « Découpez dans ces plaques des carrés tous identiques, dont les longueurs des côtés sont un nombre entier de cm, et de façon à ne pas avoir de perte. »",
          "Peut-elle choisir de découper des plaques de 10 cm de côté ?",
          "Peut-elle choisir de découper des plaques de 11 cm de côté ?",
          "On lui impose désormais de découper des carrés les plus grands possibles. Quelle sera la longueur du côté d’un carré ? ",
          "Combien y aura-t-il de carrés par plaques ?",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "theoreme-de-pythagore",
    id: "troisieme-theoreme-de-pythagore-1",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Théorème de Pythagore",
    level: "Troisième",
    number: 1,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Soit le triangle TGV rectangle en G où GT = 54 mm et GV = 72 mm.",
          "Calculer la valeur exacte de TV",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Soit le triangle YUV tel que YU = 65 mm, YV = 72 mm et UV = 97 mm.",
          "Ce triangle est-il rectangle ?",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "theoreme-de-pythagore",
    id: "troisieme-theoreme-de-pythagore-2",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Théorème de Pythagore",
    level: "Troisième",
    number: 2,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "",
          "1. Calculer AC.",
          "2. Le triangle ACD est-il rectangle ? ",
        ],
        imgName: "theoreme-de-pythagore-img1",
        solution: [],
      },
      {
        time: 300,
        question: [
          "ABCDEFGH est un parallélépipède rectangle.",
          "1. Calculer AC.",
          "2. Calculer AG.",
        ],
        imgName: "theoreme-de-pythagore-img3",
        solution: [],
      },
    ],
  },
  {
    chapterName: "theoreme-de-pythagore",
    id: "troisieme-theoreme-de-pythagore-3",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Théorème de Pythagore",
    level: "Troisième",
    number: 3,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "ABCD est un carré de côté 10 cm.",
          "Calculer EF",
          "Calculer EC",
          " Calculer FC",
          "Le triangle FEC est-il rectangle ?",
        ],
        imgName: "theoreme-de-pythagore-img2",
        solution: [],
      },
      {
        time: 300,
        question: [
          "ABCD est un rectangle de côtés AB cm 12 et AD cm 9. Sur le côté [BC] on place le point E tel que AE 13 cm. Sur le côté [DC] on place le point F tel que DF 5 cm.",
          " Calculer la longueur AF.",
          "Calculer la longueur BE.",
          "Calculer les longueurs CE",
          "Calculer les longueurs CF",
          "puis la longueur EF",
          "Le triangle AFE est-il rectangle ?",
        ],
        imgName: "theoreme-de-pythagore-img4",
        solution: [],
      },
    ],
  },
  {
    chapterName: "theoreme-de-pythagore",
    id: "troisieme-theoreme-de-pythagore-4",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Théorème de Pythagore",
    level: "Troisième",
    number: 4,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Jean-Michel est propriétaire d'un champ, représenté par le triangle ABC ci-dessous. Il achète à son voisin le champ adjacent, représenté par le triangle ADC. On obtient ainsi un nouveau champ formé par le quadrilatère ABCD. Jean Michel sait que le périmètre de son champ ABC est de 154 mètres et que BC = 56 m. Son voisin l'informe que le périmètre du champ ADC est de 144 mètres et que AC = 65 m. De plus, il sait que AD = 16 m.",
          "1. a. Justifier que les longueurs AB et DC sont respectivement égales à 33 m et 63 m.",
          "1. b. Calculer le périmètre du champ ABCD.",
          "2. Démontrer que le triangle ADC est rectangle en D. On admet que le triangle ABC est rectangle en B.",
          "3. Calculer l'aire du champ ABCD.",
          "4. Jean-Michel veut clôturer son champ avec du grillage. Il se rend chez son commerçant habituel et tombe sur l'annonce suivante : Combien va-t-il payer pour clôturer son champ? Sachant que 1mètre de grillage coûte 0,85€.",
        ],
        imgName: "theoreme-de-pythagore-img5",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Le but de l’exercice est de déterminer l’aire du triangle BCD. (OC) est la hauteur du triangle BCD issue de C. On rappelle la formule : Aire = (bxh)/2",
          "1. a. Calculer la longueur OB.",
          "1. b. Calculer la longueur OC.",
          "1. c. Calculer la longueur OD.",
          "2. En utilisant les résultats du 1, calculer l’aire du triangle BCD.",
        ],
        imgName: "theoreme-de-pythagore-img7",
        solution: [],
      },
    ],
  },
  {
    chapterName: "theoreme-de-pythagore",
    id: "troisieme-theoreme-de-pythagore-5",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Théorème de Pythagore",
    level: "Troisième",
    number: 5,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Sur le dessin ci-dessus, les points A,B et E sont alignés, et C le milieu de [BD]",
          "1. Quelle est la nature du triangle ABC ?",
          "2. En déduire la nature du triangle BDE",
          "3. Calculer ED. Arrondir le résultat au dixième.",
        ],
        imgName: "theoreme-de-pythagore-img6",
        solution: [],
      },
      {
        time: 300,
        question: [
          "ABCDEFGH est un pavé droit de longueur 4 cm, de largeur 3 cm et de hauteur 12 cm.",
          "Calculer la longueur EG",
          "Puis calculer la diagonale AG.",
        ],
        imgName: "theoreme-de-pythagore-img8",
        solution: [],
      },
    ],
  },
  {
    chapterName: "fonctions",
    id: "fonctions-1",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Fonctions",
    level: "Troisième",
    number: 1,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Soit la fonction f définie par f(x) = 8x",
          "Détermine f(2)",
          "Détermine f(-3)",
          "Détermine f(0)",
          "Quelle est l'image de -5 par la fonction f ?",
          "Quelle est l'image de $\\frac{1}{8}$ $par la fonction f ?$",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Voici un tableau de valeurs correspondant à une fonction f.",
          "Quelle est l'image de 3 par la fonction f ?",
          "Quel nombre a pour image -3 par la fonction f ?",
          "Quel nombre a pour antécédent -4 par la fonction f ?",
          "Quels sont les nombres qui ont la même image ?",
        ],
        imgName: "fonctions-img1",
        solution: [],
      },
    ],
  },
  {
    chapterName: "fonctions",
    id: "fonctions-2",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Fonctions",
    level: "Troisième",
    number: 2,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Ce graphique représente une fonction h",
          "Quelle est l'image de 0 par la fonction h ?",
          "Quels nombres ont pour image 0 par la fonction h ?",
          "Donne une valeur de : l'image de 4 par la fonction h ",
          "Donne une valeur de : l'image de -3 par la fonction h ",
        ],
        imgName: "fonctions-img2",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Sur le graphique ci-dessus, des fonctions f, g, h, k et u ont été représentées.",
          "Parmi ces fonctions, indique celles qui sont affines. (Tu préciseras celles qui sont linéaires.) (Séparer vos réponses avec des points-virgules)",
        ],
        imgName: "fonctions-img3",
        solution: [],
      },
    ],
  },
  {
    chapterName: "fonctions",
    id: "fonctions-3",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Fonctions",
    level: "Troisième",
    number: 3,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Le graphique ci-dessus représente des fonctions f et g. (Séparer vos réponses avec des points-virgules)",
          "Déterminer les images des nombres 0 ; 1 et -4.",
          "Déterminer les antécédents des nombres 3 ; -5 et 5.",
        ],
        imgName: "fonctions-img4",
        solution: [],
      },
      {
        time: 300,
        question: [
          "On considère la fonction g définie par g(x) = (x - 3)(x + 1).",
          "Quelle est l'image de 2 par g ?",
          "Quelle est l'image de -5 par g ?",
          "Quels sont les antécédents de 0 par g ?",
          "Donne un antécédent de -3 par g.",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "fonctions",
    id: "fonctions-4",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Fonctions",
    level: "Troisième",
    number: 4,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Sur le graphique ci-dessus, des fonctions f, g, h, k et u ont été représentées. Détermine chacune des cinq fonctions",
          "f(x) =",
          "g(x) =",
          "h(x) =",
          "k(x) =",
          "u(x) =",
        ],
        imgName: "fonctions-img5",
        solution: [],
      },
      {
        time: 300,
        question: [
          "La fonction k est définie par k(x) = 4x² - 3.",
          "Quelle est l'image de -0,5 par k ?",
          "Quel nombre a pour antécédent 1 par k ?",
          " Quel est l'antécédent de -3 par k ?",
          "Quels nombres ont pour image -2 par k ?",
          " Pour quelles valeurs de x a-t-on k(x) = 0 ?",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "theoreme-de-thales",
    id: "theoreme-de-thales-1",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Théorème de Thalès",
    level: "Troisième",
    number: 1,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "E est un point de [MP] et F un point de [MN]. (EF) et (PN) sont parallèles.",
          "Calculer MN.",
          "Quel est le coefficient qui permet de passer du triangle MEF au triangle MPN ?",
        ],
        imgName: "theoreme-de-thales-img1",
        solution: [],
      },
      {
        time: 300,
        question: [
          "E est un point de [AB] et F un point de [AC]. Les droites (EF) et (BC) sont parallèles.",
          " Calculer EF.",
          " Puis calculer AC.",
        ],
        imgName: "theoreme-de-thales-img2",
        solution: [],
      },
    ],
  },
  {
    chapterName: "theoreme-de-thales",
    id: "theoreme-de-thales-2",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Théorème de Thalès",
    level: "Troisième",
    number: 2,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Les droites (MN) et (BC) sont parallèles et AB= 10cm.",
          "Calculer AC.",
          "Calculer BC et AM.",
          "Le triangle ABC est-il rectangle ?",
        ],
        imgName: "theoreme-de-thales-img3",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Construis un triangle ABC rectangle en B tel que AB = 4 cm ; BC = 3 cm et AC = 5 cm. Sur la demi-droite [BA), place le point E tel que BE = 8,8 cm. Trace la droite parallèle à (AC) passant par E, elle recoupe la droite (BC) en F.",
          "Calcule EF.",
          "Calcule BF.",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "theoreme-de-thales",
    id: "theoreme-de-thales-3",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Théorème de Thalès",
    level: "Troisième",
    number: 3,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Pour gravir de très fortes pentes, un funiculaire utilise une traction par câble. Ci-dessus, un croquis d’une telle voie. La longueur DA de la voie est de 125 m.",
          "1) a) Que peux-tu dire des droites (PM) et (AH) ?",
          "1) b) Calculer MP",
          "2) a) Lorsque le funiculaire a parcouru 1 m, de quelle hauteur s’est-il élevé ?",
          "2) b) Quelle distance a parcouru le funiculaire lorsqu’il s’est élevé de 50 m ? Arrondir le résultat au dixième.",
        ],
        imgName: "theoreme-de-thales-img4",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Dans la figure ci-dessus, qui n’est pas à l’échelle, on sait que : (BC) // (DE). B, A et E sont alignés. C, A et D sont alignés.",
          "Calculer la longueur du segment [BC] ",
        ],
        imgName: "theoreme-de-thales-img5",
        solution: [],
      },
    ],
  },
  {
    chapterName: "theoreme-de-thales",
    id: "theoreme-de-thales-4",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Théorème de Thalès",
    level: "Troisième",
    number: 4,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Sur la figure ci-dessus E, G, I et F, G, H sont alignés, (EF) // (HI), EF = 25 cm , GF = 7 cm , EG = 24 cm et GH = 20 cm",
          "Quelle est la nature du triangle EFG ?",
          "Calculez KL et que K est le milieu de [HI].",
          "Calculez KI.",
        ],
        imgName: "theoreme-de-thales-img6",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Sur la figure ci-dessus, ABCD est un parallélogramme. Une droite coupe [BD] en E, [DC] en F et (BC) en G de telle sorte que AE = 5 cm et EF = 3 cm .",
          "Calculer FG",
        ],
        imgName: "theoreme-de-thales-img7",
        solution: [],
      },
    ],
  },
  {
    chapterName: "theoreme-de-thales",
    id: "theoreme-de-thales-5",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Théorème de Thalès",
    level: "Troisième",
    number: 5,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Sur la figure ci-dessus, on sait que OA = 2 ; AB = 1,6 ;  CD = 3,2 ; AC = 5,5 ; OE = 2,5 ; FD = 9 , (AC) // (BD) et (EC) // (FD).",
          "Calculez OC.",
          "Calculez BD.",
          "Calculez EF",
          "Calculez EC.",
          "Les droites (AE) et (BF) sont-elles parallèles?",
          "Sachant que le périmètre du triangle ACE vaut 14,62 ; Calculez le périmètre du triangle BDF .",
        ],
        imgName: "theoreme-de-thales-img8",
        solution: [],
      },
    ],
  },
  {
    chapterName: "proportionnalite",
    id: "proportionnalite-1",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Proportionnalité",
    level: "Troisième",
    number: 1,
    limitDate: "",
    validationDate: "",
    statements: "Proportionnalité:",
    questionsSolutions: [
      {
        time: 300,
        question: ["Compléter les tableaux de proportionnalité ci-dessus : "],
        imgName: "proportionnalite-img1",
        solution: [],
      },
      {
        time: 300,
        question: ["Compléter les tableaux de proportionnalité ci-dessus : "],
        imgName: "proportionnalite-img2",
        solution: [],
      },
    ],
  },
  {
    chapterName: "proportionnalite",
    id: "proportionnalite-2",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Proportionnalité",
    level: "Troisième",
    number: 2,
    limitDate: "",
    validationDate: "",
    statements: "Proportionnalité:",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Une feuille de papier à dessin de longueur 65 cm pèse 240 g. En supposant que la largeur reste la même",
          "Calculer la longueur, en cm, d’une feuille de papier dont la masse est de 144 g.",
          "Calculer la masse, en grammes, d’une feuille de papier mesurant 1,30 m de long.",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Un pot de 0,75 litre de vitrificateur permet de couvrir 9 m2 de parquet.",
          "Quelle quantité de vitrificateur permet de couvrir une surface de 15 m2 ?",
          "Quelle surface peut-on recouvrir avec 3 litres de vitrificateur ?",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "proportionnalite",
    id: "proportionnalite-3",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Proportionnalité",
    level: "Troisième",
    number: 3,
    limitDate: "",
    validationDate: "",
    statements: "Proportionnalité:",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Une moto de grosse cylindrée (900 cm3) consomme en moyenne 6,5 litres de sans plomb 95 pour un trajet de 130 km.",
          "Déterminer la consommation de carburant pour un trajet de 600 km.",
          "Déterminer le nombre de kilomètres parcourus si la consommation est de 18 litres.",
          "Le motard paie à une station service 0,96 € le litre de carburant. Combien dépensera-t-il pour un trajet de 850 km ?",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Dans une recette de cuisine, la quantité de pommes de terre entrant dans la composition d’un plat est proportionnelle au nombre de personnes partageant le repas.",
          " Déterminer la masse de pommes de terre nécessaire pour un repas de 6 personnes.",
          "Déterminer le nombre de personnes partageant le repas si le plat est composé de 120 g de pommes de terre.",
        ],
        imgName: "proportionnalite-img3",
        solution: [],
      },
    ],
  },
  {
    chapterName: "proportionnalite",
    id: "proportionnalite-4",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Proportionnalité",
    level: "Troisième",
    number: 4,
    limitDate: "",
    validationDate: "",
    statements: "Pourcentages:",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Avant les soldes, Mélanie avait repéré un pantalon à 70 € et un pull à 60 €. Elle décide d’attendre les soldes. Le pantalon est soldé à – 40% et le pull à – 60% .",
          "Calculer le montant du pantalon pendant les soldes",
          "Calculer le montant du pull pendant les soldes",
          "Combien Mélanie va-t-elle dépenser ?",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Clara achète 3,5 kg de pommes. Elle paie 9,10 € . ",
          "Combien coûte 8 kg de pomme ?",
          "Amélie a aussi acheté des pommes, elle en a pris 4,2 kg et elle a payé 10,5 €. Est-ce normal ?",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "proportionnalite",
    id: "proportionnalite-5",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Proportionnalité",
    level: "Troisième",
    number: 5,
    limitDate: "",
    validationDate: "",
    statements: "Pourcentages:",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Dans une entreprise, les salaires ont augmenté de 1,5% en juillet.",
          "M Dupont avait un salaire de 1650€. Quel est son salaire après cette augmentation ?",
          "Le salaire de juillet de M Legrand s’élève à 1542€. Calculer le salaire de juin.",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Un commerçant diminue ses prix de 8%.",
          "Un lecteur DVD coûte, avant réduction, 329€. Combien coûtera-t-il après ?",
          "Un écran LCD coûte, après réduction, 540€. Combien coûtait-t-il avant ?",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "proportionnalite",
    id: "proportionnalite-6",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Proportionnalité",
    level: "Troisième",
    number: 6,
    limitDate: "",
    validationDate: "",
    statements: "Pourcentages:",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Le prix d’un lecteur CD est 180€. Il est soldé au prix de 135€.",
          "Quel est le pourcentage de réduction accordée par rapport au prix initial ?",
          "Un client désire acheter cet appareil. Il possède une carte de fidélité du magasin qui lui permet de bénéficier d’une remise de 5% en caisse. Combien paiera-t-il ce lecteur ?",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Un capital est placé à 3,5% pendant 1 an a rapporté 273€ d’intérêts.",
          "Calculer le montant de ce capital.",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "proportionnalite",
    id: "proportionnalite-7",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Proportionnalité",
    level: "Troisième",
    number: 7,
    limitDate: "",
    validationDate: "",
    statements: "Pourcentages:",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Suite à un déménagement, le loyer d’une famille baisse de 18 %. Sachant que son loyer était de 580 € par mois.",
          "Détrerminer la diminution du montant du loyer.",
          "Détrerminer le prix actuel du loyer.",
        ],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Un livre neuf vaut 60 € hors taxe. Le taux de TVA est de 19,6 %.",
          "Déterminer le montant de la TVA.",
          "En déduire le prix du livre taxe comprise.",
        ],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "trigonometrie",
    id: "trigonometrie-1",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Trigonométrie",
    level: "Troisième",
    number: 1,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Complète le tableau avec le numéro du triangle qui convient.",
        ],
        imgName: "trigonometrie-img3",
        solution: [],
      },
      {
        time: 300,
        question: [
          "À l'aide de la calculatrice, calcule les valeurs, arrondies au centième, du sinus et de la tangente des angles données.",
        ],
        imgName: "trigonometrie-img4",
        solution: [],
      },
    ],
  },
  {
    chapterName: "trigonometrie",
    id: "trigonometrie-2",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Trigonométrie",
    level: "Troisième",
    number: 2,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "ABC est un triangle rectangle en A. H est le pied de la hauteur issue de A. $AH = 5\\ cm \\ \\ et \\ \\widehat{ABC} =\\ 40^\\circ$",
          "Calculer la longueur AB arrondie au dixième. ",
        ],
        imgName: "trigonometrie-img1",
        solution: [],
      },
      {
        time: 300,
        question: [
          "",
          "Calcule la longueur PK arrondie au millimètre.",
          "Déduis-en la longueur PJ arrondie au millimètre.",
        ],
        imgName: "trigonometrie-img2",
        solution: [],
      },
    ],
  },
  {
    chapterName: "trigonometrie",
    id: "trigonometrie-3",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Trigonométrie",
    level: "Troisième",
    number: 3,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "",
          "Calculer l'angle $\\widehat{URT}$",
          "Calculer l'angle $\\widehat{UTR}$",
          "Calculer l'angle $\\widehat{RUT}$",
        ],
        imgName: "trigonometrie-img5",
        solution: [],
      },
      {
        time: 300,
        question: [
          "On considère la figure ci-dessus où les points B, C et D sont alignés.",
          "Calculer la valeur exacte de la distance BC.",
          "Calculer une valeur approchée au degré de l’angle $\\widehat{BAC}$",
          "Calculer un arrondi au millimètre près de la distance BD.",
        ],
        imgName: "trigonometrie-img6",
        solution: [],
      },
    ],
  },
  {
    chapterName: "trigonometrie",
    id: "trigonometrie-4",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Trigonométrie",
    level: "Troisième",
    number: 4,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Lors d’une intervention les pompiers doivent atteindre une fenêtre F située à 18 m du sol en utilisant la grande échelle [PF]. Ils doivent prévoir le réglage de l’échelle. Le pied P de l’échelle est situé sur le camion à 1, 5 m du sol et à 10 m de l’immeuble.",
          "Avec les informations ci-dessus, calculer RF",
          "Déterminer au degré près l’angle que fait l’échelle avec l’horizontale, c’est à dire l’angle $\\widehat{FPR}$",
          "L’échelle à une longueur maximale de 25 m. Sera-t-elle assez longue pour atteindre la fenêtre ?",
        ],
        imgName: "trigonometrie-img7",
        solution: [],
      },
      {
        time: 300,
        question: [
          "",
          "Calculer la longueur EU.",
          "Calculer la mesure (arrondie à l’unité) de l’angle $\\widehat{BEU}$.",
          "Calculer la longueur AU, arrondie au mm.",
        ],
        imgName: "trigonometrie-img8",
        solution: [],
      },
    ],
  },
  {
    chapterName: "trigonometrie",
    id: "trigonometrie-5",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Trigonométrie",
    level: "Troisième",
    number: 5,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Dans la figure ci-dessus, AB = 4 cm, AD = 5 cm et AE = 7 cm. On donnera les mesures d’angles arrondies au dixième de degré et les longueurs au dixième de centimètre.",
          "Calculer l'angle $\\widehat{BAD}$.",
          "Calculer la longueur AC.",
          "Calculer la longueur CE.",
        ],
        imgName: "trigonometrie-img9",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Dans le triangle ERN, on donne : EN = 9 cm RN = 10,6 cm $\\widehat{ENR} = 60°.$ La hauteur issue de E coupe le côté [RN] en A. La parallèle à (EN) passant par A coupe le côté [RE] en T.",
          "Calculer la distance AN",
          "Calculer EA (on arrondira au dixième de centimètre).",
          "Calculer AR. ",
          "Calculer TA (on arrondira au dixième de centimètre).",
          "Calculer l’angle (on arrondira au degré) $\\widehat{ERA}$ .",
        ],
        imgName: "trigonometrie-img10",
        solution: [],
      },
    ],
  },
  {
    chapterName: "trigonometrie",
    id: "trigonometrie-6",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Trigonométrie",
    level: "Troisième",
    number: 6,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "On considère la figure ci-dessus. Les droites (AC) et (BD) s'intercepte au point O.",
          "Déterminer la mesure de l'angle (arrondie au dixième de degré près) $\\widehat{BAO}$.",
          "En déduire la mesure de l'angle $\\widehat{COD}$",
          "Déterminer le périmètre du triangle (arrondie au millimètre près) $\\widehat{ODC}$.",
        ],
        imgName: "trigonometrie-img11",
        solution: [],
      },
      {
        time: 300,
        question: [
          "Le dessin ci-contre représente la coupe d'une maison. Le triangle MAI est isocèle, de sommet principal M. La droite perpendiculaire à la droite (AI), passant par M , coupe (AI) en S. On sait que : MS = 2,5 et AI = 11. (L'unité de longueur est le mètre).",
          "Calculer AS.",
          "Calculer la valeur arrondie à 0,1 degré près de la mesure de l'angle $\\widehat{AMS}$",
          "Dans le toit, il y a une fuite en N qui fait une tache en O, sur le plafond. La droite (NO) est perpendiculaire à la droite (AI). AO = 4,5. Pour effectuer les calculs, on prendra : $\\widehat{OAN}$ = 24°. \\ $Calculer AN. (On donnera la valeur arrondie à 0,1 près).$",
        ],
        imgName: "trigonometrie-img12",
        solution: [],
      },
    ],
  },
  {
    chapterName: "trigonometrie",
    id: "trigonometrie-7",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Trigonométrie",
    level: "Troisième",
    number: 7,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [
          "Juliette mesure l'angle entre l'horizontale et le haut du réservoir d'un château d'eau grâce à un appareil placé à 1,70 m du sol. Elle trouve 58°.",
          "Calcule la hauteur du château d'eau arrondie au mètre.",
          "La contenance de celui-ci est de 500 m3 d'eau. Calcule le diamètre de la base en considérant que le réservoir du château d'eau est cylindrique. Arrondis au décimètre.",
        ],
        imgName: "trigonometrie-img13",
        solution: [],
      },
      {
        time: 300,
        question: [
          "On considère un cercle de centre O et de diamètre [BC] tel que BC = 8 cm. On place sur ce cercle un point A tel que BA = 4 cm.",
          "Faire une figure en vraie grandeur et démontrer que le triangle ABC est rectangle en A.",
          "Calculer la valeur exacte de la longueur AC. Donner la valeur arrondie de AC au millimètre près.",
          "Déterminer la mesure de l’angle $\\widehat{ABC}$.",
        ],
        imgName: "",
        graph: true,
        solution: [],
      },
    ],
  },
  {
    chapterName: "transformations",
    id: "transformations-1",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Transformations",
    level: "Troisième",
    number: 1,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [""],
        imgName: "transformations-img1",
        solution: [],
      },
      {
        time: 300,
        question: [""],
        imgName: "transformations-img2",
        solution: [],
      },
    ],
  },
  {
    chapterName: "transformations",
    id: "transformations-2",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Transformations",
    level: "Troisième",
    number: 2,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [""],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [""],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "transformations",
    id: "transformations-3",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Transformations",
    level: "Troisième",
    number: 3,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [""],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [""],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "transformations",
    id: "transformations-4",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Transformations",
    level: "Troisième",
    number: 4,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [""],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [""],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "transformations",
    id: "transformations-5",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Transformations",
    level: "Troisième",
    number: 5,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [""],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [""],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "transformations",
    id: "transformations-6",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Transformations",
    level: "Troisième",
    number: 6,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [""],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [""],
        imgName: "",
        solution: [],
      },
    ],
  },
  {
    chapterName: "transformations",
    id: "transformations-7",
    isCompleted: false,
    scoreAverage: 0,
    lesson: "Transformations",
    level: "Troisième",
    number: 7,
    limitDate: "",
    validationDate: "",
    statements: "",
    questionsSolutions: [
      {
        time: 300,
        question: [""],
        imgName: "",
        solution: [],
      },
      {
        time: 300,
        question: [""],
        imgName: "",
        solution: [],
      },
    ],
  },
];
